### ISSUE TITLE
Make panel scaling consistent between all panels

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rutherford-scattering#100]
@jessegreenberg it's good practice to have all grouped panels horizontally scaled to the same width when possible. In other words, if one expands in size, they all need to. This screenshot is with `?stringTest=double` and the Alpha Particle panel is the widest. The other two panels should be expanded to the same width in this case.
<img width="461" alt="screen shot 2016-08-05 at 2 29 39 pm" src="https://cloud.githubusercontent.com/assets/5863899/17449770/e340a3d6-5b19-11e6-9217-7fa406e63c73.png">
 
Seen on everything. For phetsims/tasks/issues/667.
Troubleshooting information (do not edit):
Name: ‪Rutherford Scattering‬:‪Rutherford Scattering‬
URL: http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-rc.1/rutherford-scattering_en.html?stringTest=double
Version: 1.0.0-rc.1 2016-08-05 18:48:42 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1920x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"1320777a","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"c45cf08f","branch":"HEAD"},"dot":{"sha":"6ee3c51e","branch":"HEAD"},"joist":{"sha":"e8a38a2c","branch":"HEAD"},"kite":{"sha":"88f0c3a0","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"rutherford-scattering":{"sha":"70a0944d","branch":"HEAD"},"scenery":{"sha":"0318877f","branch":"HEAD"},"scenery-phet":{"sha":"3cb8a1d7","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"shred":{"sha":"ea1036cf","branch":"HEAD"},"sun":{"sha":"df2905e6","branch":"HEAD"},"tandem":{"sha":"05e217d1","branch":"HEAD"}}

**Comment by amyh-phet** [comment]
@jessegreenberg    If possible, it would be great to keep the panels left aligned and have the width be consistent among all panels.

**Comment by jessegreenberg** [comment]
Should be fixed in the commits above.

**Comment by phet-steele** [comment]
Looks like this now, thanks @jessegreenberg:
<img width="460" alt="screen shot 2016-08-10 at 2 58 26 pm" src="https://cloud.githubusercontent.com/assets/5863899/17570760/f7e8352a-5f0a-11e6-9f88-249e5d6e7aa2.png">
