### ISSUE TITLE
Able to change proton count without resetting alpha particles

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rutherford-scattering#104]
Steps:
1. Macro or micro view, traces enabled for dramatic effect. Turn on alpha particles.
2. Use finger A to hold down the proton tweaker button.
3. Use finger B to grab the proton slider.
4. Release finger A, continue to slide back and forth with finger B.

Video below shows me using the neutron slider in place of the proton tweakers in Step 2, but it doesn't matter:
https://drive.google.com/file/d/0B3HJopSo_QqLT3dhQnhycko1aTA/view?usp=sharing
 Also works with the Energy slider.

Seen on Witten (iOS 9.3.2 iPad 2). For phetsims/tasks/issues/667.
Troubleshooting information:
Name: ‪Rutherford Scattering‬
URL: http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-rc.1/rutherford-scattering_en.html
Version: 1.0.0-rc.1 2016-08-05 18:48:42 UTC
Features missing: localstorage, fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"1320777a","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"c45cf08f","branch":"HEAD"},"dot":{"sha":"6ee3c51e","branch":"HEAD"},"joist":{"sha":"e8a38a2c","branch":"HEAD"},"kite":{"sha":"88f0c3a0","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"rutherford-scattering":{"sha":"70a0944d","branch":"HEAD"},"scenery":{"sha":"0318877f","branch":"HEAD"},"scenery-phet":{"sha":"3cb8a1d7","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"shred":{"sha":"ea1036cf","branch":"HEAD"},"sun":{"sha":"df2905e6","branch":"HEAD"},"tandem":{"sha":"05e217d1","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
This is actually an issue for all of the input elements in the control panels (arrow buttons, and all sliders, and scene radio buttons).

**Comment by jessegreenberg** [comment]
userInteractionProperty is now a derived property with property dependencies on the individual interactions so that the model property is not set until user interaction is finished for all elements.

**Comment by jessegreenberg** [comment]
Oops, this is still an issue with multitouch for the proton/neutron slider and the proton/neutron buttons pairs respectively.

**Comment by jessegreenberg** [comment]
Done in commit above, but still need to do radio buttons.

**Comment by jessegreenberg** [comment]
Should be resolved in the above commits.

**Comment by jessegreenberg** [comment]
Actually, we want to make sure that the new derived properties haven't introduced a memory leak.

**Comment by jessegreenberg** [comment]
Yes, significant leak introduced, must have forgotten to dispose or unlink somewhere.

**Comment by jessegreenberg** [comment]
Leak patched, I accidentally unlinked the wrong property in dispose.

**Comment by phet-steele** [comment]
Still breaks with this procedure:
1. Start in micro view (works with macro, but I'll assume you start with micro)
2. Use finger A to grab the proton slider
3. Switch to macro view
4. Switch to micro view
5. Move finger A out of the way to make room for finger B to also grab the proton slider
6. Release finger B

**Comment by jessegreenberg** [comment]
Should be fixed in the above commits, leaving open to verify as fixed in the next RC.

**Comment by phet-steele** [comment]
Verified!
