### ISSUE TITLE
Instantiate particles outside of box

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rutherford-scattering#105]
Small design quip, but I think it would be more pleasing to the eyes if alpha particles were initiated slightly below (outside) of the bounding box. This way they would enter into view smoothly instead of appearing out of thin air in a jolty manner. @jessegreenberg can you make this happen without too much trouble?

For phetsims/tasks/issues/667.

**Comment by jessegreenberg** [comment]
This is not just for particles entering the space.  Particles leaving the space exit when they are about halfway out of the bounds.

**Comment by phet-steele** [comment]
This looks so great, thanks for doing this @jessegreenberg 😄
