### ISSUE TITLE
Arrow buttons active when there are max/min nucleus

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#106]
Due to the resolution of the slider, it is possible for the right and left push buttons to be active even when the number of nucleons are at the limit.
![capture](https://cloud.githubusercontent.com/assets/6396244/17534213/590cd886-5e45-11e6-9ade-3d607278d421.PNG)

There are 100 protons, but the slider is not quite at the edge of the track, so the right push button is still enabled.

**Comment by jessegreenberg** [comment]
The value is rounded to the nearest int (via Util.roundSymmetric).  Using constrainValue function option felt too jagged during the drag, so this just snaps it to an integer on release and the result feels pretty smooth.  Thanks for pointing this this out @phet-steele.

**Comment by phet-steele** [comment]
Feels good, thanks @jessegreenberg.
