### ISSUE TITLE
Create screenshot for deployment

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#107]

**Comment by jessegreenberg** [comment]
Screen shot checked in, closing.

**Comment by phet-steele** [comment]
@jessegreenberg after the changes in #113, the screenshot is out of date. Can we get a new one at some point? 😄

**Comment by ariel-phet** [comment]
@jessegreenberg pinging on this.

**Comment by ariel-phet** [comment]
@phet-steele can you send @jessegreenberg a new screenshot....or you have the power to just put it up on github yourself.

**Comment by jessegreenberg** [comment]
I can go to campus and do this today, this requires an iPad3 and to go through step 1 of "To publish a public version" here https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md

**Comment by ariel-phet** [comment]
@jessegreenberg actually sounds like @mattpen can do this manually. I will have @phet-steele get him a screenshot. Unassigning you.

**Comment by jessegreenberg** [comment]
Excellent, thanks.  @phet-steele will still need to do this to generate the screenshot:
>Create a screenshot that is 2048x1344. Generally this is done by taking a screenshot on an iPad 3 or higher (since it has the retina display) with multiple tabs open, then crop the chrome off of it to 2048x1342, then pad the top with 2 pixels of the sim's background color (to 2048x1344) and save as /assets/$SIM-screenshot.png. Eventually, quick and easy creation of this screen shot will be supported through the screenshot feature from the PhET menu, but as of this writing this support doesn't exist.

**Comment by phet-steele** [comment]
@amyh-phet may you comment about what should be in the screenshot now? Even though macro view is fronted in the sim, I don't feel it is worthy to be a screenshot. It's smaller, messier, and busier than micro view.

Some unedited comparisons, brought down to approximate size:

<img src=https://cloud.githubusercontent.com/assets/5863899/18521345/f5d867fe-7a68-11e6-837b-081e2042a46d.PNG width="300" height="197">

<img src=https://cloud.githubusercontent.com/assets/5863899/18520972/66bae598-7a67-11e6-8f2b-b1b2e7887cb1.PNG width="300" height="197">

**Comment by amyh-phet** [comment]
@phet-steele    I agree that the macro view is really cluttered and doesn't make a great screen shot.  I like the second screen shot with the nuclear view.  Thanks for getting this updated.

**Comment by jessegreenberg** [comment]
We may as well generate a new README for the repo too once the screenshot is updated.

**Comment by jessegreenberg** [comment]
Since the build server resizes the images automatically, I will need to do a maintenance release for this.

**Comment by jessegreenberg** [comment]
> e may as well generate a new README for the repo too once the screenshot is updated.

The readme pulls directly from github so it is already up to date.

**Comment by jessegreenberg** [comment]
Done, new screenshot visible on the site.
