### ISSUE TITLE
multitouch issues

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#108]
Out of https://github.com/phetsims/tasks/issues/675, @phet-steele found some new multitouch issues

1)  Interaction with the control panel while holding down the step button causes #104
2) Pressing reset all while interacting with the control panel will cause #104 once the gun is turned back on

@phet-steele please add to this issue if you find more multi-touch issues.

**Comment by jessegreenberg** [comment]
The issues listed in the original comment should be fixed, but leaving issue open in case any more come out of phetsims/tasks#675.

**Comment by phet-steele** [comment]
Performance tested on

Win 10 Chrome
OSX 10.11.6 Chrome
iPad 2 iOS 9.3.4
Chromebook

All good.

**Comment by jessegreenberg** [comment]
@phet-steele did you find any more multitouch issues?

**Comment by phet-steele** [comment]
No.
