### ISSUE TITLE
Nucleus node doesn't always update in Firefox and iPad2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#109]
From phetsims/tasks#675, @phet-steele noticed that the canvas icon node for the rutherford nucleus does not update.  Occasionally, if the slider is quickly dragged, the nucleus is not redrawn and the trace is left in the screen view.
![capture](https://cloud.githubusercontent.com/assets/6396244/17706142/18e2dd70-6398-11e6-8133-584ce5e20e62.PNG)

**Comment by jessegreenberg** [comment]
The above commit should fix this.  I tested on an iPad2 and Firefox, and I can no longer reproduce this issue.  Leaving open for verification for the next RC.

**Comment by phet-steele** [comment]
@jessegreenberg, myself nor @alynne-phet can reproduce this anymore.
