### ISSUE TITLE
rutherford-scattering fails assertion on startup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#11]
In requirejs mode with assertions enabled, here's the stack trace:

Uncaught Error: Assertion failed: undefinedwindow.assertions.assertFunction @ assert.js:22extend.setVisible @ Node.js?bust=1440524428290:2294(anonymous function) @ ToggleNode.js?bust=1440524428290:44inherit.link @ Property.js?bust=1440524428290:166ToggleNode @ ToggleNode.js?bust=1440524428290:43BooleanRoundToggleButton @ BooleanRoundToggleButton.js?bust=1440524428290:22PlayPauseButton @ PlayPauseButton.js?bust=1440524428290:61AnimationControlView @ AnimationControlView.js?bust=1440524428290:29RutherfordAtomView @ RutherfordAtomView.js?bust=1440524428290:56Screen.call.backgroundColor @ RutherfordAtomScreen.js?bust=1440524428290:34inherit.initializeView @ Screen.js?bust=1440524428290:103inherit.initializeModelAndView @ Screen.js?bust=1440524428290:114(anonymous function) @ Sim.js?bust=1440524428290:392St @ lodash-2.4.1.min.js?bust=1440524428290:23Sim @ Sim.js?bust=1440524428290:390(anonymous function) @ rutherford-scattering-main.js?bust=1440524428290:29doneLoadingImages @ SimLauncher.js?bust=1440524428290:31launch @ SimLauncher.js?bust=1440524428290:51(anonymous function) @ rutherford-scattering-main.js?bust=1440524428290:28

**Comment by jakies** [comment]
Having a hard time finding this intuitively, hopefully it goes away as I start updating the project.

**Comment by jonathanolson** [comment]
I thought I'd take a shot at this (~10min?) since it's regularly showing up on automated testing, and I've found at least 4 places where number Properties are being used for booleans.

I'd solve that, but there's energyProperty:
```js
// TODO: take the property from the model somewhere.
var energyProperty = new Property( 1 ); // model.alasdf
```

It's used both as a numeric value (for HSlider) and as a boolean value (for the Show Traces checkbox). I really don't know WHEN it should be a boolean, so I'm bailing out on this.

**Comment by jakies** [comment]
It shouldn't be used as either, it's a dummy I had used as I was exploring
the functionalities of the HSlider module. You can delete that line and
null anything that references it

**Comment by pixelzoom** [comment]
rutherford-scattering removed from active-runnables. Closing.
