### ISSUE TITLE
Add QA credits

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#110]
I forgot to add QA credits in the latest release and they need to be added.  @phet-steele would you please provide the list of names that should go in these credits?

**Comment by phet-steele** [comment]
Steele Dalton, Amanda Davis, Bryce Griebenow, Andrea Lin, Ben Roberts, Bryan Yoelin

**Comment by jessegreenberg** [comment]
QA credits have been added in 1.0.1 maintenance release.
