### ISSUE TITLE
adjust touchArea options for HSlider thumb

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#111]
In https://github.com/phetsims/sun/issues/254, the touchArea defaults for HSlider thumb were changed so that they default to pixels, not a percentage of the thumb size.  Sims that use HSlider's `thumbSize` option will therefore need to also specify `thumbTouchAreaXDilation` and `thumbTouchAreaYDilation`.

**Comment by schmitzware** [comment]
I just pulled all and took a look at this. Still seems reasonable. 


![screen shot 2016-08-30 at 11 51 19 am](https://cloud.githubusercontent.com/assets/694045/18102649/260b1c22-6ea8-11e6-85c2-a3fd9ac444ca.png)

**Comment by pixelzoom** [comment]
Possible collision with the "Traces" check box?

**Comment by schmitzware** [comment]
Right..  just curious.. why doesn't the checkbox show the touch area? Is it always just the box or does it only show if it's been changed from the defaults?

**Comment by pixelzoom** [comment]
touchArea and mouseArea are only shown if they have been explicitly set. They default to the Node's bounds. In the case of a CheckBox, the bounds includes the box and the label to the right of it.

**Comment by schmitzware** [comment]
gotcha.. thanks.

**Comment by schmitzware** [comment]
How's this?

![screen shot 2016-08-30 at 2 12 44 pm](https://cloud.githubusercontent.com/assets/694045/18107233/019dd2b2-6ebc-11e6-9311-0226825f7e0c.png)

**Comment by pixelzoom** [comment]
Seems OK.  If it were me, I'd probably add a little vertical space between slider and check box.

**Comment by schmitzware** [comment]
3rd times a charm?

![screen shot 2016-08-30 at 3 05 28 pm](https://cloud.githubusercontent.com/assets/694045/18108894/64b958d8-6ec3-11e6-8ce6-4a7b62ac56a8.png)


https://github.com/phetsims/rutherford-scattering/commit/b1c8c4de4d5a758eb6f6ca1341cc9d38178afc07

**Comment by pixelzoom** [comment]
👍 Closing.
