### ISSUE TITLE
AlphaParticlePropertiesPanel constructor doc

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#112]
Noticed while participating in https://github.com/phetsims/rutherford-scattering/issues/111 ...

Doc for AlphaParticlePropertiesPanel constructor is being flagged as incorrect by IDEA. Parameter `showTracesProperty` doesn't exist, doc for parameter `content` is missing.

```js
  /**
   * Constructor for a Alpha Particle Properties control panel.
   *
   * @param {AlphaParticlePropertiesPanelContent} showTracesProperty - content for the panel
   * @param {Object} [options]
   * @constructor
   */
  function AlphaParticlePropertiesPanel( content, options ) {
```

**Comment by schmitzware** [comment]
Passing this to Jesse.. I did my IDEA formatting time before handing it off.. ;)

**Comment by jessegreenberg** [comment]
JSDoc fixed above, sorry about that.  Closing.
