### ISSUE TITLE
Consider opening the sim in the atomic view

### ISSUE THREAD

**Issue by arouinfar** [phetsims/rutherford-scattering#113]
During status, Robert reported about using Rutherford Scattering in class. He and the students thought the atomic view (showing several atoms) was a more natural starting point than the nuclear view. Assigning to @amyh-phet for consideration.

**Comment by ariel-phet** [comment]
@amyh-phet if we make this change, we should also flip the vertical order of the scene selection

**Comment by amyh-phet** [comment]
@ariel-phet    The chemist in me loves this change.   Would this be back to @jessegreenberg for implementation?

**Comment by amyh-phet** [comment]
@jessegreenberg   Looks like you are off the hook!    Assigning to @pixelzoom.   Can we do the following:

1) Rutherford atom screen opens to Atom scene.
2) Move scene selection buttons so that Atom is at top and Nucleus is second.

**Comment by pixelzoom** [comment]
Done. Published in maintenance release 1.0.2.  @amyh-phet please verify and close.

https://phet.colorado.edu/sims/html/rutherford-scattering/latest/rutherford-scattering_en.html

**Comment by amyh-phet** [comment]
Looks great.  I think it will take me longer to change the Teacher Tips in powerpoint than it took you to change the sim!

**Comment by kathy-phet** [comment]
I checked out the live version and it looks good to me! Thanks.
