### ISSUE TITLE
fails stringTest in Options dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#118]
With `?stringTest=xss`, it's apparent that the Options dialog's content has no `maxWidth`.

If doing a maintenance release, you need to pickup the fix for the "Options" title in https://github.com/phetsims/joist/issues/416.

**Comment by jessegreenberg** [comment]
This sim will be redeployed off of master, assigning to myself to make sure this was addressed.

**Comment by jessegreenberg** [comment]
This sim is being redeployed out of master which contains this fix. Closing.
