### ISSUE TITLE
Replace PropertySet with Property

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#119]
From phetsims/axon#102, PropertySet is deprecated and should be replaced with Property.

**Comment by pixelzoom** [comment]
Some things that I noticed related to this:

(1) `Atom.reset` is calling `PropertySet.reset`, but it's not a `PropertySet`.  You can likely just remove this call.

(2) `RGBBaseModel.reset` should be calling `this.gun.reset`, not `this.gun.onProperty.reset`.

**Comment by jessegreenberg** [comment]
Great, thanks @pixelzoom Ill watch for these as we proceed with this issue.

**Comment by jessegreenberg** [comment]
Done in the above commits. Closing.
