### ISSUE TITLE
use StringUtils.format for filling in parameterized strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#12]
Here's the anti-pattern in question:

You have this string in rutherford-scattering-strings_en.json, where '?' is a placeholder that you want to fill in:

```js
  "pattern.nuclearScale": {
    "value": "? fm (nuclear scale)"
  }
```

Then you want to replace the '?' with a value in RutherfordAtomView:

```js
20 var scaleString = require( "string!RUTHERFORD_SCATTERING/pattern.nuclearScale" );
150 scaleString = scaleString.replace('?', RSConstants.NUCLEAR_SCALE_DEFAULT);
```

That works if you only have one parameter to fill in. But it's not a good general solution.

The preferred pattern is as follows:

Use Java's MessageFormat pattern for strings that require placeholders. Placeholder are integers surrounded by curly brackets.  In your case:

```
  "pattern.nuclearScale": {
    "value": "{0} fm (nuclear scale)"
  }
```

Then in RutherfordAtomView:

```js
+ var StringUtils = require( 'PHETCOMMON/util/StringUtils' );
20 var scaleString = require( "string!RUTHERFORD_SCATTERING/pattern.nuclearScale" );
150 scaleString = StringUtils.format( scaleString, RSConstants.NUCLEAR_SCALE_DEFAULT);
```

For other examples, search other PhET sims for StringUtils.format.

**Comment by pixelzoom** [comment]
Here's a general example, which you could type into the browser console.

```js
> var sentence = 'The {0} brown {1} ran over the {2}.';
> console.log( StringUtils.format( sentence, 'big', 'truck', 'pig' ) );
The big brown truck ran over the pig.
> console.log( StringUtils.format( sentence, 'little', 'dog', 'hill' ) );
The little brown dog ran over the hill.
```

**Comment by ariel-phet** [comment]
I am guessing this is no longer an issue since Jake's work was removed, closing
