### ISSUE TITLE
inconsistent light perspective

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/rutherford-scattering#130]
I just noticed that this button has a light perspective from the bottom left, which is inconsistent with the other buttons in this sim and all of our sims. 
![screen shot 2017-11-21 at 10 42 12 am](https://user-images.githubusercontent.com/7852916/33087758-c0ea2812-cea8-11e7-918b-13d9690ac639.png)

It should be changed so the light is coming from the top left, like these buttons:
![screen shot 2017-11-21 at 10 43 43 am](https://user-images.githubusercontent.com/7852916/33087811-e09dd60e-cea8-11e7-87dc-aa042720c412.png)

**Comment by jessegreenberg** [comment]
Fixed in the above commit, here it is in master:
![capture](https://user-images.githubusercontent.com/6396244/33092074-469817f0-ceb6-11e7-97c4-8778e469b2cf.PNG)

**Comment by jessegreenberg** [comment]
Closing.
