### ISSUE TITLE
NumberControls should be centered in panels

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#132]
Noticed in an a11y meeting, the NumberControls aren't centered in the panels. In this screenshot,  one can see  they are left aligned with the panel titles.
![capture](https://user-images.githubusercontent.com/6396244/34449462-bb7aa836-ecb5-11e7-9a5c-c12ae6ae588b.PNG)

Would be nice to center NumberControls in panels before next deploy.

**Comment by jessegreenberg** [comment]
Assigning to myself to look into  or delegate depending on timeline.

**Comment by jessegreenberg** [comment]
It looks like they are off center so that all panel content is generally left aligned, but the spacing of titles make it look like the NumberControls should be centered. By centering, it looks like this:
![master](https://user-images.githubusercontent.com/6396244/44547550-81cbad80-a6e9-11e8-9b27-8ec90955be3a.PNG)

Compared to what it looks like in the published version:
![website](https://user-images.githubusercontent.com/6396244/44547548-7f695380-a6e9-11e8-8525-0bfd59d86cec.PNG)

**Comment by jessegreenberg** [comment]
This seems like an OK change, almost unnoticeable but I want to make sure, @arouinfar does this seem OK?

**Comment by arouinfar** [comment]
@jessegreenberg not sure why the numberControls weren't centered to begin with, so I'm definitely on board with this change.

**Comment by jessegreenberg** [comment]
OK, thanks. Ill commit the change and close.

**Comment by jessegreenberg** [comment]
Reopening, I notice layout shifts slightly when changing scenes.

**Comment by jessegreenberg** [comment]
OK, fixed with the above commit,
