### ISSUE TITLE
User suggestion: histogram borders

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rutherford-scattering#134]
> Watching the impacts on the HTML5 sim, it occurred to me that it would be a really cool feature (I'm not going to claim easy to implement) if the border of the experiment area would act as a histogram, either increasing the size of a column with each hit, or perhaps changing from white to purple (the color of the alphas) in gradual steps. 
> 
> It could give a good visual of the frequency of hits at various angles from incident, even if it's on the square border of the experiment area.

**Comment by jessegreenberg** [comment]
This sim will be redeployed off of master in the near future, @ariel-phet @oliver-phet how would you like to handle this suggestion?

**Comment by oliver-phet** [comment]
I think this would normally be up to the lead (AH). So AP/KP?

**Comment by ariel-phet** [comment]
@oliver-phet @jessegreenberg 

Although I think this is an interesting suggestion, I think we will not implement it for two reasons:

1. From a practical point of view, we just do not have the bandwidth/time

2. Perhaps more importantly, I am not sure how accurately the model in Rutherford scattering reflects actual experimental results. This sim is made to be more qualitative, and I think adding such a histogram would require us to make sure we were matching experimental values. Currently, I think the sim covers the learning goals quite well, especially with the addition of the atomic view.

**Comment by ariel-phet** [comment]
@oliver-phet please let the user know that although this is an interesting suggestion it is beyond the scope of the sim and its current model. Feel free to close.
