### ISSUE TITLE
Traces should be same color on both atomic and nuclear scenes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#137]
For both views, the traces should be violet on both scenes of the "Rutherford Atom" screen.

**Comment by jessegreenberg** [comment]
This will clarify that both scenes are emitting the same alpha particles at different intensity.

**Comment by jessegreenberg** [comment]
Done in the above commit. @arouinfar could you please review this change on master? IMO the violet trace is more difficult to see against the red in the plum pudding screen.

In the nuclear scene of the Rutherford atom screen, maybe a darker color would look  better?  I think it looks better in the atomic scene because the traces become transparent as they fade out.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! I don't think we had considered the Plum Pudding screen at all. The contrast between the traces and plum pudding is pretty awful, so I wouldn't  advocate for violet traces on that screen. Perhaps we can leave them gray on the Plum Pudding screen? The two screens represent different models, so perhaps the discontinuity in trace color isn't as important. Thoughts @ariel-phet?

**Comment by ariel-phet** [comment]
@jessegreenberg @arouinfar yes, I think leaving traces gray on the Plum Pudding screen would be fine.

The traces are sort of "ether" anyhow, representing an idea of the path not an actual physical object, so I think the discontinuity between screens will not be a problem. I think having them them unified on the first screen is an improvement, but I don't think any damage is done leaving them gray on the plum pudding screen.

**Comment by arouinfar** [comment]
Sounds good, thanks @ariel-phet. I'll leave it to you @jessegreenberg.

**Comment by phet-steele** [comment]
@arouinfar go ahead and review on master if you would please.

**Comment by arouinfar** [comment]
Looks good to me. Thanks @phet-steele!

**Comment by jessegreenberg** [comment]
Thanks @phet-steele!
