### ISSUE TITLE
Boxes on Plum Pudding screen do not line up when stringTest=double

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/rutherford-scattering#145]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Firefox
**Problem description:**
For phetsims/QA/issues/181
Related to phetsims/rutherford-scattering/issues/100
When using stringTest=double the Legend and Alpha Particle boxes no longer are aligned at the right edge.  They are when no string test is used, and should remain so per @arouinfar.
**Steps to reproduce:**
1. Set stringTest=double
2. Go to the Plum Pudding screen
3. Examine the Legend box and compare to the Alpha Particle box.

**Screenshots:**
![pudding](https://user-images.githubusercontent.com/41024075/44816665-26ddfe80-aba0-11e8-8885-1720dce602b2.PNG)

<details>
<summary>Troubleshooting Info</summary>

Name: ‪Rutherford Scattering‬:‪Rutherford Scattering‬
URL: https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.0-rc.1/phet/rutherford-scattering_en_phet.html?stringTest=double
Version: 1.1.0-rc.1 2018-08-27 15:43:03 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"41b1cf6b","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"f1a7eb07","branch":"HEAD"},"dot":{"sha":"e9a91d91","branch":"HEAD"},"joist":{"sha":"b5a39dff","branch":"HEAD"},"kite":{"sha":"08b2dbf9","branch":"HEAD"},"phet-core":{"sha":"3ec304bd","branch":"HEAD"},"phet-io":{"sha":"e42116c4","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"39a153bd","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"868e17c8","branch":"HEAD"},"phet-io-wrappers":{"sha":"97461ad8","branch":"HEAD"},"phetcommon":{"sha":"1dba8704","branch":"HEAD"},"query-string-machine":{"sha":"21fd2a0a","branch":"HEAD"},"rutherford-scattering":{"sha":"8a497095","branch":"HEAD"},"scenery":{"sha":"fc52c939","branch":"HEAD"},"scenery-phet":{"sha":"6027f56d","branch":"HEAD"},"sherpa":{"sha":"16fe1a7e","branch":"HEAD"},"shred":{"sha":"ef01bf40","branch":"HEAD"},"sun":{"sha":"1ae5c99a","branch":"HEAD"},"tambo":{"sha":"1995a421","branch":"HEAD"},"tandem":{"sha":"c9b53278","branch":"HEAD"}}

</details>

**Comment by lmulhall-phet** [comment]
Seeing this on iOS 11 too.

**Comment by jessegreenberg** [comment]
This is also an issue in the published version. One way to fix this would be to put legend items into an AlignGroup to ensure that they all have the same heights.

**Comment by jessegreenberg** [comment]
I went ahead with https://github.com/phetsims/rutherford-scattering/issues/145#issuecomment-418457600, and this fixes the issue with stringTest=double. But it doesn't fix the issue for stringTest=long. All of the content in each legend is the same height, but the text is scaled down more in the "Atomic" scale (because of the extra length of the "- - -" icon) so there is still a slight shift in the layout for that test.

Based on https://github.com/phetsims/rutherford-scattering/issues/145#issuecomment-417514011, and my understanding of stringTest=long, I think this is OK. @KatieWoe can you please make sure this is fixed in master?

**Comment by KatieWoe** [comment]
@jessegreenberg Sorry, but stringTest=double looks the same on master.

**Comment by jessegreenberg** [comment]
Sorry, I totally misread the issue and fixed something else...I fixed an issue where the panels shifted with stringTest=double when switching from "Nuclear" to "Atom" scenes in the Rutherford Atom screen. Working on this one next.

**Comment by KatieWoe** [comment]
@jessegreenberg Looks good on master.

**Comment by jessegreenberg** [comment]
Thanks for testing @KatieWoe, then I will go ahead and merge commits into the release branch.

**Comment by phet-steele** [comment]
Good in 1.1.0-r.2.
