### ISSUE TITLE
Resize of nucleus question

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/rutherford-scattering#148]
Should the circular line always appear when resizing the nucleus in the nuclear scale scene?  I have found some conditions where it does not.  For instance, if using the number spinner to adjust on a mac 10.13 with a track pad, if you gently tap the lines do not appear, but they do appear if you press down so the track pad "clicks."
For phetsims/QA/issues/181

**Comment by jessegreenberg** [comment]
Good question @KatieWoe. I can also do this if I click really fast with my mouse in Chrome on Windows 10. IMO this is not a big deal, my understanding is that the circular line was added for performance reasons, because changing the nucleus didn't draw very quickly. @arouinfar can you please comment?

**Comment by arouinfar** [comment]
>  my understanding is that the circular line was added for performance reasons, because changing the nucleus didn't draw very quickly

Makes sense @jessegreenberg. In Java, the dashed circle appears when changing the number of particles with the slider, but it doesn't appear when text is directly entered.

![rutherford-changingn-java](https://user-images.githubusercontent.com/8419308/45058822-15409f00-b057-11e8-8acd-51c27e0e59aa.gif)


In HTML5, it seems a bit jumpy when the dashed circle intermittently appears when using the tweakers.
![rutherford-changingn](https://user-images.githubusercontent.com/8419308/45058236-3dc79980-b055-11e8-8fb4-69827c7b5bd1.gif)

@jessegreenberg would it be possible to just not show the circle for a single tweaker press? It looks smooth when using the slider or when the tweaker fires-on-hold, so I wouldn't change the behavior there.

**Comment by jessegreenberg** [comment]
@arouinfar it is! Can you please review the behavior on master? If it looks OK ill merge into the release branch.

**Comment by arouinfar** [comment]
Looks good to me @jessegreenberg! 

@KatieWoe can you also take a look?

**Comment by KatieWoe** [comment]
Just took a look on Win 10 Chrome.  I think it looks very nice.

**Comment by arouinfar** [comment]
Great! Reassigning to @jessegreenberg to merge into the release branch.

**Comment by phet-steele** [comment]
Working fine for moi in 1.1.0-rc.2.
