### ISSUE TITLE
Plum Pudding Particles don't change direction

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/rutherford-scattering#150]
For https://github.com/phetsims/QA/issues/194 on the plum pudding screen none of the alpha particles change direction when moving over the electrons within the atom.  This is especially noticeable when the particles have their trace on them. I'm not sure if this is the intended behavior, but it seems like the particles should change direction like they do on the Rutherford atom screen. I have attached a screenshot of the particles with the trace, showing how none of them change direction at all. This has occurred on Windows 10 v. 1803.17134.285 on the latest versions of Chrome, Firefox, and Edge.
![rutherford_straight](https://user-images.githubusercontent.com/30352536/45976381-d4a7c600-c003-11e8-8a0b-a47fd08d5787.JPG)

**Comment by phet-steele** [comment]
@JRomero0613 this is on purpose and a learning goal of the sim. https://en.wikipedia.org/wiki/Geiger%E2%80%93Marsden_experiment
