### ISSUE TITLE
Misaligned string in Plum pudding screen.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/rutherford-scattering#151]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/194
Possibly related to https://github.com/phetsims/rutherford-scattering/issues/145
The strings and images in the Legend toolbox are improperly centered, leading to too much empty space to their left.  Most noticeable when strings are short.
**Steps to reproduce:**
1. Set stringTest=X
2. Go to the plum pudding screen
3. Examine legend toolbox.

**Screenshots:**
![rc](https://user-images.githubusercontent.com/41024075/46026152-dc20ab00-c0a7-11e8-8967-9c857b3e5ad4.PNG)
![short](https://user-images.githubusercontent.com/41024075/46026157-dfb43200-c0a7-11e8-833e-23b52a4a62cd.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪Rutherford Scattering‬
URL: https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.0-rc.2/phet/rutherford-scattering_all_phet_debug.html
Version: 1.1.0-rc.2 2018-09-24 15:59:53 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"41b1cf6b","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"f1a7eb07","branch":"HEAD"},"dot":{"sha":"e9a91d91","branch":"HEAD"},"joist":{"sha":"b5a39dff","branch":"HEAD"},"kite":{"sha":"08b2dbf9","branch":"HEAD"},"phet-core":{"sha":"3ec304bd","branch":"HEAD"},"phet-io":{"sha":"e42116c4","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"39a153bd","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"868e17c8","branch":"HEAD"},"phet-io-wrappers":{"sha":"97461ad8","branch":"HEAD"},"phetcommon":{"sha":"1dba8704","branch":"HEAD"},"query-string-machine":{"sha":"21fd2a0a","branch":"HEAD"},"rutherford-scattering":{"sha":"eda36d5a","branch":"HEAD"},"scenery":{"sha":"fc52c939","branch":"HEAD"},"scenery-phet":{"sha":"6027f56d","branch":"HEAD"},"sherpa":{"sha":"16fe1a7e","branch":"HEAD"},"shred":{"sha":"ef01bf40","branch":"HEAD"},"sun":{"sha":"1ae5c99a","branch":"HEAD"},"tambo":{"sha":"1995a421","branch":"HEAD"},"tandem":{"sha":"c9b53278","branch":"HEAD"}}

</details>

**Comment by jessegreenberg** [comment]
Adding the "pending testing" label to make sure this looks OK in the next RC.

**Comment by KatieWoe** [comment]
Looks good 1.1.0-rc.3
