### ISSUE TITLE
unnecessary ColorProfile listeners

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#156]
Noticed while working on https://github.com/phetsims/joist/issues/569...

In ScaleInfoNode.js:

```js
    // when the color profile changes, update the fill of all associated children
    // no need to dispose, instance exists for life of sim
    RSGlobals.projectorModeProperty.link( function() {
      var labelColor = RSColorProfile.panelLabelColorProperty;
      
      // update end marker fill
      leftMarker.stroke = labelColor;
      rightMarker.stroke = labelColor;

      rightArrowNode.fill = labelColor;
      leftArrowNode.fill = labelColor;

      labelText.fill = labelColor;
    } );
```

This is listener is unnecessary.  Just set the fills and strokes for these Nodes to `RSColorProfile.panelLabelColorProperty` and scenery will take care of it.

**Comment by pixelzoom** [comment]
Self-assigning, I'll take care of this as part of phetsims/joist#569.

**Comment by pixelzoom** [comment]
Another one in RSBaseScreenView:

```js
   // when the color profile changes, the alpha source text should be black
    // no need to unlink since the text will exist for life of sim
    RSColorProfile.panelLabelColorProperty.linkAttribute( alphaSourceText, 'fill' );
```

alphaSourceText should just be instantiated with `fill: RSColorProfile.panelLabelColorProperty`.

**Comment by pixelzoom** [comment]
Addressed in the above commit, tested using PhET Menu > Options > Projector Mode.

@jessegreenberg would you mind reviewing?

**Comment by pixelzoom** [comment]
I found some more suspect code in `PlumPuddingAtomScreenView`:

```js
    // whenever the color profile changes, redraw the control panel
    // this screen view exists for life of sim, no need to unlink
    RSGlobals.projectorModeProperty.link( function() {
...
```

**Comment by pixelzoom** [comment]
And some more in `AtomCollectionNode`:

```js
    // draw the atom space whenever the color profile changes
    // no need to unlink, this instance exists for life of sim
    RSGlobals.projectorModeProperty.link( function() {
...
```

**Comment by pixelzoom** [comment]
And more in `RutherfordAtomScreenView`.  Ugh.

```js
    // when the color profile changes, create a new control panel
    // no need to unlink, screen view exists for life of sim
    RSGlobals.projectorModeProperty.link( function() {
...

    // if the bacgrkound, panel or stroke colors change, draw a new button group
    // no need to unlink, screen view exists for life of sim
    RSGlobals.projectorModeProperty.link( function() {
...
```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/joist/issues/569, I changed the above-mentioned links from `RSGlobals.projectorModeProperty.link` to `RSColorProfile.profilePropertyName.link`, because a separate BooleanProperty is not longer needed for ProjectorModeCheckbox.

**Comment by pixelzoom** [comment]
I discussed via Zoom with @jessegreenberg.  The listeners in `PlumPuddingAtomScreenView` and `RutherfordAtomScreenView` seemed to be unnecessary (colors updated automatically via scenery), so I removed them.  Then I compared projector and default modes with the published version (1.1.4) to verify.

We thought that this listener in `AtomCollectionNode` was unnecessary, and could be entirely removed:

```js
    // draw the atom space whenever the color profile changes
    // no need to unlink, this instance exists for life of sim
    RSColorProfile.profileNameProperty.link( function() {
      drawAtomSpace();

      // update the image
      self.image = self.toImage( function( image, x, y ) {
        self.image = image;
      } );
    } );
```

But I now see `atomsNode.image` used in `AtomSpaceNode`.  So I'm not sure what to do here, and I'm not really clear on where/how `AtomCollectionNode` is being used.  It seems like the goal is to convert this Node to an image, then regenerate that image if colors change.  But that means we should listening to whichever color Properties are used by `AtomSpaceNode`, since they could be changed either via `profileNameProperty` or via rutherford-scattering-colors.hmtl.

@jessegreenberg would you mind taking it from here?

**Comment by jessegreenberg** [comment]
AtomCollectionNode draws the actual nuclei and electron shells in the "Atom" scene of the "Rutherford Atom" screen, and it is eventually drawn with canvas using context.drawImage which is why it is using toImage.

The only color that changes with color profile is `RSColorProfile.nucleusColorProperty`, the circles are always grey.

**Comment by jessegreenberg** [comment]
I just tried to test and rutherford-scattering-colors.html doesn't seem to be changing any colors at all.

**Comment by jessegreenberg** [comment]
> But that means we should listening to whichever color Properties are used by AtomSpaceNode, since they could be changed either via profileNameProperty or via rutherford-scattering-colors.hmtl.

This was done in https://github.com/phetsims/rutherford-scattering/commit/8f1dc135252c23f808e86add917eddae21c6afb0. I made an issue for the unused colors in RSColorProfile https://github.com/phetsims/rutherford-scattering/issues/163, so I think this can be closed.  @pixelzoom thanks for removing the listeners that weren't necessary.
