### ISSUE TITLE
Address model inconsistency in Teacher Tips

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/rutherford-scattering#16]
From https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3606

Since this is called the "plum pudding" screen, we should probably address this valid point in the teacher tips

> Dear Sir,
> 
> Firstly let me say how absolutely excellent your simulations are! I have been using them with my classes for years, and have found them remarkably helpful. They represent a serious, major, contribution to Physics education.
> Secondly, there is a rare error in the simulation of Rutherford Scattering (which I used this morning with my Sixth Form class):
> 
> In the Plum-Pudding Model section, the gold atom is represented by a big red blob (The positive charge), with the blue dots being the electrons. So far, so good. But then the incoming Helium ion (alpha particle) is represented by two protons and two neutrons in a tiny combination. This is wrong, because if the positive charge in the gold atom is a big red blob, then the alpha particle is also a big red blob – indeed, one of about the same size (but without the blue dots).
> 
> Unfortunately this implies a complete reconstruction of this part of the simulation.
> 
> Thanks again for having created such an outstanding educational resource.

**Comment by amyh-phet** [comment]
Addressed in new version of teacher tips that will be uploaded with HTML5 version of sim.
