### ISSUE TITLE
RSBaseModel uses field defined in its subclasses

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#160]
Noted while investigating #158.

`RSBaseModel` uses `userInteractionProperty`, which is not undefined in `RSBaseModel`. It's defined in subclasses RutherfordAtomModel and PlumPuddingModel.  Reaching down in the class hierarchy is a definite no no.

**Comment by jessegreenberg** [comment]
Thanks, a big no-no. Also, this is duplicated in the two subtypes and should be moved to RSBaseModel.
```js
    var userInteractionListener = function( userInteraction ) {
      if ( userInteraction ) {
        self.removeAllParticles();
      }
    };
```

**Comment by jessegreenberg** [comment]
`userInteractionProperty` is now a param for RSBaseModel, created and passed in from each subtype. @pixelzoom would you mind reviewing?

**Comment by pixelzoom** [comment]
👍 closing.
