### ISSUE TITLE
RSBaseScreenView controlPanel is immediately disposed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#161]
Noted while investigating #158.

`RSBaseScreenView` creates `this.controlPanel`, line 195:

```js
    // @protected - collect all control panels in a single panel
    this.controlPanel = this.createControlPanel( controlPanels );
    this.addChild( this.controlPanel );
```

`RutherfordAtomScreenView` and `PlumPuddingAtomScreenView` are the only subclasses of `RSBaseScreenView`.   One of the first things they do is dispose of `this.controlPanel ` and create a new one.  E.g. in `PlumPuddingAtomScreenView` constructor:

```js
    RSBaseScreenView.call( this, model, scaleString, createSpaceNode, {
      includePlumPuddingLegend: true
    } );

    // dispose and remove the old control panel
    this.removeChild( this.controlPanel );
    this.controlPanel.dispose();
...
    this.controlPanel = this.createControlPanel( panels );
    this.addChild( this.controlPanel );
```

**Comment by pixelzoom** [comment]
This was added to `RutherfordAtomConstructor` for #156 

```
    // {Node} control panel is created below by sceneProperty listener, to correspond to scene
    this.controlPanel = null;
```

That's a problem, the control panel created by `RSBaseScreenView` doesn't get removed or disposed.

**Comment by pixelzoom** [comment]
@jessegreenberg I went ahead a fully addressed this.  I removed `this.controlPanel` from `RSBaseScreenView`, and made the subclasses fully responsible for `controlPanel`.   Please review.

**Comment by pixelzoom** [comment]
Btw... I compared master to the published version, to verify that the control panels looked the same.  And I tested with `?ea&fuzz`.

**Comment by jessegreenberg** [comment]
Awesome, looks great thanks. I also compared against published version and the layout looks the same.
