### ISSUE TITLE
Not all colors in RSColorProfile are used

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#163]
It is possible at one time these colors were used to control the sim with rutherford-scattering-colors.html, but they aren't hooked up in the sim now. We could either use these colors and attach listeners in the sim to fix rutherford-scattering-colors.html or remove them.

I would remove them unless someone thinks the color picker tool is worth maintaining. What do you think @pixelzoom?

**Comment by pixelzoom** [comment]
I'm fine with removing the colors, if you think that's appropriate.

**Comment by jessegreenberg** [comment]
OK, unused colors removed.
