### ISSUE TITLE
Several items missing in iOS 13

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/rutherford-scattering#164]
For https://github.com/phetsims/QA/issues/427
The icon for the first screen is missing both on the home screen and within the sim on iOS 13.  It is there in iOS 12.
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/65085479-7f2e9c80-d96b-11e9-97bc-c8ac7642c98e.png)

**Comment by KatieWoe** [comment]
Edit: Much larger problem in the sim.  The alpha particles don't show up on the second screen, and the close up on the first screen is completely gone.

**Comment by KatieWoe** [comment]
Occurs in published.

**Comment by jessegreenberg** [comment]
OK thanks @KatieWoe. It sounds like most of the protons and neutrons are missing. They are painted in an atypical way in this sim. For instance, see RutherfordNucleusNode.RutherfordNucleusIcon which uses inner class IconCanvasNode.

**Comment by jessegreenberg** [comment]
The particles use CanvasNode and the rendering context method drawImage. Wondering if it is related to those. @KatieWoe can you please try one of these other use cases of this to see if things show up as expected?

- Molecules in the magnifying glass in acid-base-solutions.
- Minus charges in the wall in balloons and static electricity

**Comment by KatieWoe** [comment]
Molecules in acid-base-solutions look fine to me.
Charges look fine in BASE

**Comment by jessegreenberg** [comment]
Thanks for checking. Points to either something more specific to the sim or something else entirely.

**Comment by jessegreenberg** [comment]
This is caused by https://github.com/phetsims/sun/issues/526. Being investigated there.

**Comment by jessegreenberg** [comment]
This was patched as part of https://github.com/phetsims/sun/issues/526 and can now be closed.
