### ISSUE TITLE
Consider "macro" view?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/rutherford-scattering#17]
User suggestion from unfuddle https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3495

@amyh-phet can you look at this and comment if you think this would be something we should consider adding?

> Would be helpful if the sim had a tab for a macro view of "what was observed in the experiment".  Would be helpful if the Rutherford tab could zoom out to roughly the size of the atom, to show how alpha particles that don't come close to the nucleus are not deflected.  In some chemistry books, Rutherford scattering is shown as alpha particles "bouncing off" (as in, colliding with) of the nucleus.  Would be helpful to show a more zoomed out view that looks more like this, and the more zoomed in view (what the sim currently has) to show the deflection from repulsive positive charges.

**Comment by ariel-phet** [comment]
and from https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3670

> 
> I hope you can pass these comments on to whoever is thinking about the design of the Rutherford scattering simulator.
> 
> Looking for a simulator on nuclear fusion, I discovered the Rutherford scattering simulator.  I have been looking for a way to teach about this so I was particularly interested.  Thanks to the PhET project for making this!   I see the simulator does what one would ask it to - it shows alphas deflecting  near a nucleus.
> 
> I am wishing for something more, however, to convey a sense of the scale in atoms.   I have not done this experiment myself and maybe I should, but what Rutherford found when looking at the paths of alphas was that the vast majority of them passed through nearly undeflected because most alphas never passed even remotely near a nucleus, at the atomic scale.  This was the most important observation - that usually not much happened - and the other important observation was that a very few alphas deflected into very wild angles.
> 
> I’m teaching about radiation literacy and one of the big ideas - relevant to the penetration of radiation particles through matter - is that matter is mostly empty space.  The Rutherford experiment seems like the ideal pathway for helping students to see this.
> 
> So I wish for a “zoom out” feature in the Rutherford experiment simulator that would show the vast numbers of alphas that go right through a thin gold foil or whatever.  So we could see that the ones that are deflected are actually very rare. I think this is the key observation to make in this sim.
> 
> The modern nuclear theory of the atom couldn’t be developed until radiation had been discovered.

**Comment by ariel-phet** [comment]
I am sensing a theme here...

From https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3680

> Hi,
> 
> Rutherford expected and observed that most alpha particles went straight through undeflected. His conclusions was that an atom is mostly empty space.
> 
> The current simulation scale means that most alpha particles are deflected. It was only about 1 in 2000 that were deflected by large angles.
> 
> If there was a way of making the scale larger, it may be able to show this, but at the moment the simulation is not useful for us to reinforce Rutherford’s findings.
> 
> Thank you very much for your brilliant simulations

**Comment by amyh-phet** [comment]
Yes - definitely a theme of chemistry is to have students understand both the macroscopic and submicroscopic views of matter.   I agree that adding this feature to the sim would make the sim a more useful tool to help students understand Rutherford's discovery that most of the atom is empty space.  If possible to incorporate this, I think we should.

**Comment by ariel-phet** [comment]
Well then @amyh-phet guess who should work on a super sweet mockup? :smile: 

This would be fairly high priority to mockup since this sim is about to get worked on...

**Comment by amyh-phet** [comment]
Sounds good.  Thoughts on when the sim might be up for design meeting?

**Comment by ariel-phet** [comment]
It could be this week if we want...but next week at the latest if we are considering this addition

**Comment by amyh-phet** [comment]
Great! I'll be ready for this week if we have time on the schedule.  Would be good to discuss how best to implement this with the design team.

**Comment by ariel-phet** [comment]
Closing and making a new issue to cover the macro view implementation.
