### ISSUE TITLE
Sim uses default layoutBounds, shred uses non-default layoutBounds.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#175]
This sim uses default layoutBounds for ScreenView.  But one of its dependencies (shred) requires non-default layoutBounds.  In ShredConstants.js:

```
  LAYOUT_BOUNDS: new Bounds2( 0, 0, 768, 464 ),
```

I don't know whether/how this might be affecting this sim. But other sims (e.g. build-an-atom) that use shred have been forced to use these `ShredConstants.LAYOUT_BOUNDS` for their ScreenViews.  So it might be worth investigating why this working (or not working), etc.

See also https://github.com/phetsims/shred/issues/37 and https://github.com/phetsims/phet-io/issues/1939.

**Comment by marlitas** [comment]
I confirmed that the LayoutBounds in Shred were not affecting this sim. Closing
