### ISSUE TITLE
redesign: orbit of electron

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#18]
@ariel-phet asked me to create this issue after a Skype discussion.

The "Rutherford Atom" screen has a feature that's not very obvious. It shows an electron orbiting the atom.  Only a tiny piece of the orbit  is visible, and it's difficult to notice when the electron appears.  Here's a screenshot from the Java version, with a green arrow added to point to the electron (blue dot).  Consider a "zoom out" feature so that you can see the electron moving through its full orbit.

![orbit](https://cloud.githubusercontent.com/assets/3046552/12762711/bb96f338-c9ad-11e5-9a9a-2b242787002f.jpg)

**Comment by ariel-phet** [comment]
@amyh-phet can you include a mockup in this issue that shows the new version of this scene without the electron orbit?

**Comment by amyh-phet** [comment]
New mock up attached.  Note that changes to scene buttons (nucleus, atom) will likely change and mockups will be updated.

![rutherford_scattering_no_electron_02_25_16](https://cloud.githubusercontent.com/assets/13650180/13328854/45047f3e-dbae-11e5-9405-3c00931737b1.png)

**Comment by ariel-phet** [comment]
@amyh-phet are there supposed to be dotted lines in the bottom right and left and corners?

**Comment by amyh-phet** [comment]
I think these dotted lines should also be removed if we are adding the macro view scene to the sim.  The dotted lines in the original sim show the electron much closer to the nucleus than it actually is.  From reading notes from the original sim design, the orbiting electron was included to represent the idea that there were electrons in the atom, but the deflection of the alpha particles was due entirely to the massive, positively charged nucleus.    If we are going to present a scaled representation of electrons in the macro view, I think we need to be consistent with our scale on the nuclear screen as well.

**Comment by ariel-phet** [comment]
OK, please remove the dotted lines, we are not going to publish the sim until the macro view is done (although probably not done by Dave).

**Comment by amyh-phet** [comment]
Updated artwork included.
![rutherford_atom_no_electron_02_25_16](https://cloud.githubusercontent.com/assets/13650180/13331955/02e0dab2-dbbd-11e5-9e29-a63c7c816f78.png)

**Comment by ariel-phet** [comment]
@schmitzware updated artwork above, (don't worry about the nucleus vs atom button you will not be implementing those)

**Comment by schmitzware** [comment]
There is no orbiting electron or dotted path in the new HTML sim. Ok if I close this?

**Comment by amyh-phet** [comment]
Close away!
