### ISSUE TITLE
Use ObservableArray for Particles and added/removed events in AtomModel.js

### ISSUE THREAD

**Issue by samreid** [phetsims/rutherford-scattering#19]
At the beginning of AtomModel's constructor, there are these declarations:

```js
    this.particles = [];  // all active alpha particle models
    this.particleAddCallbacks = []; // @protected called when a alpha particle is added
    this.particleRemoveCallbacks = []; // @protected called when a alpha particle is removed
```

Then `addParticle` is declared like so:

```js
    /**
     * @param {AlphaParticleModel} alphaParticle
     * @public
     */
    addParticle: function( alphaParticle ) {

      this.particles.push( alphaParticle );

      // call registered callbacks
      var callbacks = this.particleAddCallbacks.slice( 0 );
      for ( var i = 0; i < callbacks.length; i++ ) {
        callbacks[ i ]( alphaParticle );
      }
    },
```

A simpler alternative would be to use Axon for sending the events.

`AXON/ObservableArray` provides an array with built-in functions for sending notifications when items are added or removed.  This is probably the best approach for this case, but if there are other constraints that require you to use a separate array here, then you could alternatively use `AXON/Emitter` for sending the events.  I'd suggest to try ObservableArray first and see if that will work.

**Comment by samreid** [comment]
@schmitzware we often find it productive as a team to make a GitHub issue comment describing how/why a particular decision was made (in addition to the commit message).  In this case, the commit message says:

```
Fixed issues, added reset of model on user interaction, added separate atom nodes, profiled and reworked rendering for performance

Issue #23
Issue #19 - Old implementation/ObservableArray is no longer needed.
```

But it does not explain why the ObservableArray is no longer needed. From looking in the code, it seems like this is because you have switched from rendering the particles+paths as scenery nodes to rendering them in a CanvasNode.  Is this correct?

For an example of an issue that has a good commit message and elaboration in the issue, please see:
https://github.com/phetsims/hookes-law/issues/10

Here's another issue that shows a good comment after commit (though generally if someone else created the issue, it would be assigned back to them to verify):
https://github.com/phetsims/forces-and-motion-basics/issues/163

Part of this is also so that your message will show up in an email trail.  Commits don't send email notifications but comments do, so it is helpful to give a note in an issue comment before reassigning (even if it says something as simple as "fixed as prescribed, reassigning to @samreid for review").

Also, we often use a single line for the commit messages, some team members put the issue numbers at the beginning of the commit message and some at the end.  Here's a link to @pixelzoom's commits for hookes-law so you can get a sense of the style.
https://github.com/phetsims/hookes-law/commits/master?page=4

We've never discussed this explicitly, but I believe the reason for this is that some tools in our toolchain are more suited to the single line commit messages.  Of course unusual cases may call for many line commit messages, but I suspect these would be rare.

Reassigning to @schmitzware to confirm the reason ObservableArray is no longer needed and to discuss our group's commit and issue commenting strategies, please let me know if you have any questions.

**Comment by schmitzware** [comment]
Yes, at the time, the old implementation which included the ObservableArray, was using a scenery nodes  to render the particles. I was originally keeping track of these separately from corresponding the model using the ObservableArray. In the revised implementation, particles are rendered using the particle model positions and image in the CanvasNode. No need for nodes any more.

**Comment by samreid** [comment]
Thanks @schmitzware, closing.
