### ISSUE TITLE
Have electrons as part of plum pudding image?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/rutherford-scattering#21]
@schmitzware asked the following question:

> I was talking with Sam today and he pointed me toward you for this question. In the Rutherford Scattering sim, specifically the Plum Pudding model, the old Java sim is populating the plum pudding image with the electrons in the code. I noticed that these don’t contribute to the simulation at all. Their positions seem irrelevant.  Anyway, I wanted to ask you if we should just bake them in to the plum pudding image itself. Looks like that image is changing (according tot he design doc).

This seems like a reasonable change to me since the electrons are static in this screen and merely representative.

Do you agree @amyh-phet and if so, can you provide @schmitzware with a new image?

**Comment by amyh-phet** [comment]
@schmitzware  @ariel-phet   I think this is a very reasonable change as the electrons don't interact with the alpha particles in this screen.   Will send an image to @schmitzware that includes electrons for plum pudding model.

**Comment by pixelzoom** [comment]
Make sure that @amyh-phet provides the Illustrator file, and that it gets checked in to assets/.

**Comment by pixelzoom** [comment]
@amyh-phet This appear to be done. Can it be closed?

**Comment by amyh-phet** [comment]
Yes. Closing.
