### ISSUE TITLE
Tweaks to "gun" to make it not feel like a laser

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/rutherford-scattering#22]
@amyh-phet we had discussed some tweaks to the alpha particle gun to make it look less like a "laser"

I suggest the following:

- change the body color to something funky like green or such
- change the button color, the red used is very much the archetypal laser pointer red, maybe blue or such
- it looks like the body length can be changed, and I think the squat body is good, but if the width can be changed, perhaps increase the width some so the aspect ratio looks less laser like
- perhaps put a label on it or underneath that says "alpha beam" but uses the "alpha particle" symbol
![alphasymbol](https://cloud.githubusercontent.com/assets/4051174/13239990/b7d85504-d99b-11e5-97ee-663aba6e6839.jpg)

**Comment by amyh-phet** [comment]
Will work on tweaks to this and will update design doc accordingly.

**Comment by amyh-phet** [comment]
Alpha particle source should be modified as follows:

1) Change body color to look more like a brass covering on body.
2) Change button to aqua blue color
3) Add alpha source label using greek letter for alpha to bottom of source.
4) Enlarge body width to accommodate text.

![alpha_source](https://cloud.githubusercontent.com/assets/13650180/13680818/79c93c1e-e6b7-11e5-8942-5e2bc8de1367.png)

If you would like hex codes for any colors used in mock up, please let me know.

**Comment by pixelzoom** [comment]
@amyh-phet Yes, please supply colors that you've used in the above mockup. RGB is preferable to hex.

**Comment by pixelzoom** [comment]
For the button, please provide both the "on" and "off" colors.

**Comment by pixelzoom** [comment]
Putting the label on the body is an i18n problem - we'll need to scale the text to fit, and it will undoubtedly be unreadable in some languages.  Would it be OK to put the label below the source?

**Comment by pixelzoom** [comment]
Can you also provide a mockup with the source shown in context?  Impossible to tell from this mockup what the dimensions should be.

**Comment by pixelzoom** [comment]
@amyh-phet 

(1) Yes, please supply colors that you've used in the above mockup. RGB is preferable to hex. For the button, please provide both the "on" and "off" colors.

(2) Putting the label on the body is an i18n problem - we'll need to scale the text to fit, and it will undoubtedly be unreadable in some languages. Would it be OK to put the label below the source?

(3) Can you also provide a mockup with the source shown in context? Impossible to tell from this mockup what the dimensions should be.

**Comment by pixelzoom** [comment]
Thanks @amyh-phet.

@schmitzware that should be enough info to proceed. Back to you.

**Comment by schmitzware** [comment]
Amy - how's that look?

![screen shot 2016-03-10 at 1 59 23 pm](https://cloud.githubusercontent.com/assets/694045/13686020/78544642-e6c8-11e5-87b2-80f54794107c.png)

**Comment by amyh-phet** [comment]
Beautiful!  Can we change the text to read "particles' instead of "source"?

**Comment by pixelzoom** [comment]
Test with `?dev&stringTest=long`, looks like `maxWidth` is a tad too large.  Change RSBaseScreenView line 77 to `maxWidth: 200`.

**Comment by pixelzoom** [comment]
![screenshot_19](https://cloud.githubusercontent.com/assets/3046552/13687331/d794177c-e6d7-11e5-8913-9c99dca0c005.png)

**Comment by pixelzoom** [comment]
@amyh-phet Just out of curiosity... Why is "Alpha Particle" used for the control panel, while "α particles" is used on the "gun"?

**Comment by amyh-phet** [comment]
Happy to make this consistent across sim.  I hadn't caught this so I'm glad you brought it up. Let's go with "alpha particle" for consistency.

**Comment by pixelzoom** [comment]
I thought you might have used "α particles" to save space, when the label was on the gun. Now that it's below the gun, there's more space.

**Comment by pixelzoom** [comment]
And did you mean 'alpha particles' (plural) as the label on the gun?  You indicated 'alpha particle' (singular).

**Comment by amyh-phet** [comment]
Yes, plural on the gun as it is capable of emitting many alpha particles.  And yes, the label was shorter with "α particles" so my guess is that might be where the symbol originally came from.   

I think it is best to keep "alpha particle" singular in the control panel and legend.

**Comment by schmitzware** [comment]
Now I'm confused - gun label:
"alpha particles" or "α particles"

**Comment by pixelzoom** [comment]
Agreed, confusing. @amyh-phet's comments aren't very consistent about upper/lowercase. E.g "keep 'alpha particle' singular in the control panel", when the control panel is currently labeled 'Alpha Particle'.

PhET typically capitalizes each word, and that's what is done elsewhere in this sim. So I recommend labeling the gun "Alpha Particles".  @amyh-phet is that OK, or is there some reason why it should be lowercase?

**Comment by amyh-phet** [comment]
One more try - sorry, I was trying to get to class and wasn't very clear.

Gun label:  "Alpha Particles"
Legend label:  "Alpha Particle"
Panel label: "Alpha Particle"

Let me know if you have more questions.

**Comment by pixelzoom** [comment]
Reopening.  Looks like the new key is the string file is still "alphaSource", should be "alphaParticles".  We try to keep these somewhat close to the key value, at least to start.

**Comment by schmitzware** [comment]
string key change in 79d756d6b3fb524ef5fbc95346a26d78a7bee20f

**Comment by pixelzoom** [comment]
```
% grunt lint
Running "eslint:repoFiles" (eslint) task

/Users/cmalley/PhET/GitHub/rutherford-scattering/js/common/view/RSBaseScreenView.js
  37:3  error  Mismatched var in require(string!), key=alphaParticles, var=alphaSourceString, desiredVar=alphaParticlesString  string-require-statement-match

✖ 1 problem (1 error, 0 warnings)

Warning: Task "eslint:repoFiles" failed. Use --force to continue.

Aborted due to warnings.
```

This means that you also have to change the require statement in RSBaseScreenView, line 37:

```var alphaSourceString = require( 'string!RUTHERFORD_SCATTERING/alphaParticles' );```

While you're in there... RSBaseScreenView line 72:

```var alphaSourceText = new Text(```

Change var name to `alphaParticlesText`.   

Sorry if these seem like nits. But for maintenance, we often go looking for strings based on the string that's displayed on the screen.  And string keys are displayed to translators in Rosetta.

**Comment by pixelzoom** [comment]
Btw... The above lint error is from a custom PhET rule.  For a `require` call that involves the `string!` plugin, it requires that the var name must be the string key with 'String' suffix added.  So if the string key is "foo" then you need `var fooString = ...`

**Comment by schmitzware** [comment]
this is getting ridiculous.. I'll fix it tomorrow.
