### ISSUE TITLE
Buggy path with trace on

### ISSUE THREAD

**Issue by samreid** [phetsims/rutherford-scattering#24]
I observed this on the iPad3 during performance testing, one particle took an odd trajectory and got stuck:

![image](https://cloud.githubusercontent.com/assets/679486/13438286/a19e5814-dfa5-11e5-9e0f-6b12ac4d0169.png)

**Comment by samreid** [comment]
I reloaded the sim and ran tethered for 5 minutes and did not see the issue again, perhaps it is very rare!

**Comment by schmitzware** [comment]
Hummm... I've left this running on my iPad2 all afternoon with no luck in duplicating it..  Any suggestions??

**Comment by pixelzoom** [comment]
Add an assertion that checks for sudden trajectory change, and run it unattended overnight?

**Comment by samreid** [comment]
Other options: code review of RutherfordAtomModel.moveParticle to see if anything seems suspicious.  

Also, if we cannot reproduce this bug then it seems OK to close this issue. (We can reopen if it crops up in subsequent testing).

**Comment by samreid** [comment]
This doesn't address values between 0 and X0_MIN, how about testing `x<X0_MIN` instead?
```js
      var x0 = Math.abs( initialPosition.x );
      if ( x0 === 0 ) {
          x0 = X0_MIN; // algorithm fails for x0 < X0_MIN
      }
```

**Comment by samreid** [comment]
I don't know where the math came from, but how can we be certain all Math.sqrt args are non-negative?  And the divisors are non-zero?  Those seem like potential causes of odd trajectories.

**Comment by schmitzware** [comment]
The math all came from the java sim.  I can add calcs to intermediate values for all the sqrt/div can check those.

**Comment by schmitzware** [comment]
I've still not been able to reproduce it. I've gona ahead and addressed both the X0_MIN & 0 sqrt/divisors suggestions in <67139e114bec7906bcedfc7431bc1284b4a03fb6>
Closing this for now, if it pops up in QA will revisit then.

**Comment by samreid** [comment]
Sounds good, thanks @phetsims/schmitzware!

**Comment by pixelzoom** [comment]
I suppose the algorithm for trajectories is specified in doc/trajectories.pdf.  Compare the (ported) implementation to the specification, in case there was a bug in the Java implementation.

**Comment by pixelzoom** [comment]
Reopening. 

The algorithm for trajectories is specified in doc/trajectories.pdf.  Recommended to compare the (ported) implementation to the specification, in case there was a bug in the Java implementation.

Or if you want to stick with the plan of reopening if it pops up in QA, that would be ok too.

**Comment by pixelzoom** [comment]
@schmitzware I noticed that in master, the default values for number of Protons and Electrons are now 79 and 118 respectively, which corresponds to the values in the screenshot shown in https://github.com/phetsims/rutherford-scattering/issues/24#issue-137657847. I don't believe these are the correct default values.  Did you inadvertently push values that were being used for testing this issue?

**Comment by pixelzoom** [comment]
Mea culpa. Those are the default values in the Java implementation.

**Comment by schmitzware** [comment]
The design doc has "default: 79 protons and 118 neutrons (gold)"

--  
Dave Schmitz
Schmitzware, LLC.

**Comment by schmitzware** [comment]
I'd like to stick with the QA path. We saw it once so far. I haven't been able to reproduce it running it overnight. I've added catches for all -sqrt calls and / by 0s which, as Sam mentioned, are good possibilities for that behavior. If it pops up again I'm happy to dig deeper.
