### ISSUE TITLE
Target material zoom box perspective

### ISSUE THREAD

**Issue by schmitzware** [phetsims/rutherford-scattering#25]
ChrisM had suggested the zoom box on the target material should have a similar perspective as the material itself.  For example:

![screen shot 2016-03-01 at 11 48 49 am](https://cloud.githubusercontent.com/assets/694045/13439791/f2a96eee-dfa3-11e5-8a87-1771da7b35f5.png)

![screen shot 2016-03-01 at 11 45 40 am](https://cloud.githubusercontent.com/assets/694045/13439800/fb244e7c-dfa3-11e5-8a0f-7e48b8145d52.png)

**Comment by amyh-phet** [comment]
@schmitzware  I like adding the perspective to the zoom box on the target material.  I will adjust mockups to reflect this change.

**Comment by schmitzware** [comment]
Perfect. Thanks!
