### ISSUE TITLE
Location of "Reset" button

### ISSUE THREAD

**Issue by schmitzware** [phetsims/rutherford-scattering#26]
So, right now I have the reset button at the bottom of the property panels - like so:
![screen shot 2016-03-01 at 3 51 17 pm](https://cloud.githubusercontent.com/assets/694045/13446599/ac32bc24-dfc9-11e5-83a7-17513628b135.png)

![screen shot 2016-03-01 at 3 51 24 pm](https://cloud.githubusercontent.com/assets/694045/13446603/b1dd4e78-dfc9-11e5-9b73-b11cb2fdfa9e.png)

Is this correct? Or should it be in the same place on both screens?

**Comment by amyh-phet** [comment]
@schmitzware   The reset all button should be in the same location on both screens.    The button should be located in the lower right portion of the screen near the PhET menu bar.   I think the location looks good on the first screen shot (Rutherford Model) but needs to move down on the Plum Pudding model.
![reset_all_location](https://cloud.githubusercontent.com/assets/13650180/13447267/60cac200-dfd7-11e5-9560-ad785a6ac020.png)

**Comment by schmitzware** [comment]
Gotcha. Thanks!
