### ISSUE TITLE
Need icons for both screens

### ISSUE THREAD

**Issue by schmitzware** [phetsims/rutherford-scattering#27]
![screen shot 2016-03-01 at 3 36 20 pm](https://cloud.githubusercontent.com/assets/694045/13446640/f4ce3ee0-dfc9-11e5-98e7-3c81def74606.png)

**Comment by amyh-phet** [comment]
@schmitzware    I'll be working to get these done over the next two days.   I would like to run them by the design team before sending you the artwork if that is okay.

**Comment by schmitzware** [comment]
You bet! Thanks!

**Comment by pixelzoom** [comment]
Make sure that @amyh-phet provides the Illustrator file, and that it gets checked in to assets/.

**Comment by amyh-phet** [comment]
@schmitzware  I just sent you the screen icon AI files.  Please use a black background with the screen icon.   Let me know if I need to make any changes to the files.  Thanks for your patience!
