### ISSUE TITLE
margin on arrow buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#31]
@ariel-phet requested that the arrow buttons (aka "tweakers") should have margins that look more like hookes-law.

It looks like you just need to use the defaults. Remove these lines in AtomPropertiesPanel and you'll be good to go:

```js
76      xMargin: 3,
77      yMargin: 3,
```

**Comment by schmitzware** [comment]
Thanks for that.. 
Fixed in 9b7b76b3906e7f625d12566c7da2a16de2593d51

**Comment by pixelzoom** [comment]
:+1: Closing.
