### ISSUE TITLE
representation of atom while editing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#33]
When changing the number of Protons or Neutrons, the atom changes to a circle, whose radius changes.  In the Java version, the circle was dashed and white; in HTML5 version it's a solid and orangish.  Was this a change request?

**Comment by schmitzware** [comment]
fixed in 9b7b76b3906e7f625d12566c7da2a16de2593d51

**Comment by pixelzoom** [comment]
Looks good. I'd recommend one deviation from the Java version. Change OUTLINE_STROKE_COLOR to 'white' (Java used 'gray').  It will "pop" more, and will be clearly visible on projectors (a significant issue in the classroom).

**Comment by schmitzware** [comment]
Fixed in eab268222d5210d2c3c64cfea2b6b7fd196021fe

**Comment by schmitzware** [comment]
Sorry I should have done that as it's own commit..

**Comment by pixelzoom** [comment]
:+1: Closing.
