### ISSUE TITLE
missing model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#36]
Related to #30 (code review).

This file is currently empty.  It's typically ported from (newer) Java sims, but this sim was old enough not to have this file.  Look at some other examples, then let's talk about what should be done.

**Comment by schmitzware** [comment]
.txt or .md? looks like there's a mix of both throughout the repo.

**Comment by pixelzoom** [comment]
We recently standardized on .md (GitHub markdown).

**Comment by pixelzoom** [comment]
:+1: Closing.
