### ISSUE TITLE
loose ends for image files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#37]
I'm doing code review (#30) before images have been finalized (#21,#27,#28), so I'm going to skip these checklist items:

> - [ ] Is there a file in assets/ for every file in audio/ and images/?
> - [ ] Are all license.json files populated? audio/license.json and images/license.json should enumerate all files in those directories. For the format of license.json files, go here.

Loose ends:

(1) Use .png for all image files.

(2) Put files used to create the images (typically .ai, Adobe Illustrator files) in assets/. Ideally there is one .ai file for each .png file. But in some situations (like the screen icons) there may be one .ai file that contains icons. If that's the case, then the .ai should contain *only* the icons, not other unrelated artwork (eg mockups). If the .ai file doesn't meet these requirement, kick it back to the creator. (Mentioning @amyh-phet here so that she's aware of these requirements.)

(3) Replace '???' in license.json with name of the person who created the images (probably @amyh-phet).

**Comment by amyh-phet** [comment]
@pixelzoom @schmitzware Working on assets for Rutherford scattering.  Hopefully have them early next week.  Sorry for the delay.
