### ISSUE TITLE
code formatting problem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#39]
Looks like there's a general problem with formatting.

In every source file, there's an extra space after the token `function`, e.g.:
`define( function ( require ) {`

The correct formatting is no space after `function`, e.g.:
`define( function( require ) {`

I worked with @schmitzware to set up IntelliJ IDEA to use the PhET codestyle (i.e., phet-idea-codestyle.iml), so I know that the source files were formatted.  So perhaps this is a problem with phet-idea-codestyle.iml.  

Low priority to investigate. In the meantime, I'll reformat.

**Comment by pixelzoom** [comment]
The relevant entry in phet-idea-codestyle.iml is probably:

```<option name="SPACE_BEFORE_FUNCTION_LEFT_PARENTH" value="false" />```

This looks suspicious, since `PARENTHESES` is spelled out in other options.

**Comment by schmitzware** [comment]
Hummm.. I don't even see a 'SPACE_BEFORE_FUNCTION_LEFT_<ANYTHING>' in the XML file I have here.. I took it from phet-info/ide

**Comment by pixelzoom** [comment]
I checked $HOME/Library/Preferences/IntelliJIdea15/codestyles/phet-idea-codestyle.xml, and `SPACE_BEFORE_FUNCTION_LEFT_PARENTH` is also there, so it's not being overwritten by IDEA.

**Comment by pixelzoom** [comment]
`SPACE_BEFORE_FUNCTION_LEFT_PARENT` is not responsible for the problem. That option (which is apparently just inconsistently named) adds a space when the function is *called*, not after the `function` token.

**Comment by pixelzoom** [comment]
The option that controls this is accessed via this check box: Preferences -> Editor -> CodeStyle -> Javascript -> Before Parentheses -> Function declaration parentheses.   

When checked, this is written to the .xml file:

```<option name="SPACE_BEFORE_METHOD_PARENTHESES" value="true" />```

When unchecked, this is written to the .xml file:

```<option name="SPACE_BEFORE_METHOD_CALL_PARENTHESES" value="true" />```

And the latter is what's currently in the version of phet-idea-codestyle.xml that's checked into GitHub.

Note that these are 2 different option names, and that their values are both true.  So I suspect an IDEA bug here.  But I don't understand what @schmitzware experiencing this options as "checked".

**Comment by pixelzoom** [comment]
@schmitzware let me know when you have a few minutes to pair with me on this.

**Comment by pixelzoom** [comment]
Note to self: This is a general issue, not specific. It should be moved to phet-info, where phet-idea-codestyle.xml lives.

**Comment by pixelzoom** [comment]
Moved to https://github.com/phetsims/phet-info/issues/14. Closing.
