### ISSUE TITLE
buggy instantiation of GunTargetNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#44]
Related to #30 (code review).

Looks like a bug in how the GunTargetNode is instantiated.  It's constructor signature is:

```function GunTargetNode( model, options )```

Call sites in PlumPuddingAtomScreenView and RutherfordAtomScreenView are:

```js
var gunTargetNode = new GunTargetNode( model, showAlphaTraceProperty, scaleFormattedString, {
      left: this.layoutBounds.left + 75,
      top: this.layoutBounds.top + RSConstants.PANEL_TOP_MARGIN
    } );
```
So I'm not sure how this layout code is working.

**Comment by schmitzware** [comment]
This is all me..

**Comment by pixelzoom** [comment]
The layout options at the call sites are indeed being ignored.  Looks like Node is appearing in the correct location because layout is hardcoded in `GunTargetNode` constructor:

```js
    var targetMaterialNode = new TargetMaterialNode( {
      left: 60,
      bottom: 200
    } );
```

**Comment by pixelzoom** [comment]
Before you fix this, you might want to review https://github.com/phetsims/rutherford-scattering/issues/49#issuecomment-193006272, where I've proposed to delete GunTargetNode.

**Comment by schmitzware** [comment]
I started fixing this on Fri so I just went ahead and completed it.. I'll look at #49 today.

**Comment by pixelzoom** [comment]
Looks like you removed the layout options to GunTargetNode in RutherfordAtomScreenView:

```47 var gunTargetNode = new GunTargetNode( model.gun );```

But not in PlumPuddingScreenView:

```js
    var gunTargetNode = new GunTargetNode( model.gun, {
      left: this.layoutBounds.left + 75,
      top: this.layoutBounds.top + RSConstants.PANEL_TOP_MARGIN
    } );
```

This is probably why things are shifting right as reported in https://github.com/phetsims/rutherford-scattering/issues/34#issuecomment-193385294.

**Comment by schmitzware** [comment]
I forgot about the plum pudding screen - this is fixed..

**Comment by schmitzware** [comment]
I take it back.. :)

**Comment by pixelzoom** [comment]
Confirmed. Closing.
