### ISSUE TITLE
anti-pattern for using options in PropertySet subtypes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#47]
Related to #30 (code review).

RutherfordAtomModel and PlumPuddingModel are the "container" models for the 2 screens. They extend RSBaseModel, which extends PropertySet.  The way that options are used in this hierarchy is little bit of an anti-pattern. 

(1) "Container" models rarely need options. If they do have options, those options are typically not Properties.

(2) RSBaseModel mixes Properties and non-Properties in options.  For example, `bounds` is an option, so it becomes a Property, even though it never changes.  It should in fact be a `@public (read-only)` field in RSBaseModel. 

(3) Specifying additional Properties through options is a bit unclear. You need to look inside the supertype to see that it extends PropertySet, and that the options will actually become Properties. In cases like this, it's clearer to call the supertype constructor, then use `addProperty` to add additional Properties.

**Comment by pixelzoom** [comment]
In this case, it was more expedient for me to demonstrate by making the change, see above commit. Let me know if you have any questions.

**Comment by schmitzware** [comment]
(2) makes perfect sense to me. Thanks for pointing that out. 
For (3), Properties are now created two different ways - alphaParticleEnergy and proton/neutron counts.  I don't necessarily agree with the importance of it but it's fine with me. 

Should I just close this?

**Comment by pixelzoom** [comment]
Yup, fine to close. I'll do so.
