### ISSUE TITLE
duplication in ScreenView subtypes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#49]
Related to #30 (code review).

There's some duplication in RutherfordAtomScreenView and PlumPuddingScreenView. I ran out of time today to investigate further and make recommendations.  Assign to myself to look at on 3/7/16.

**Comment by pixelzoom** [comment]
Note to self: @schmitzware commented a bit on this issue in https://github.com/phetsims/rutherford-scattering/issues/30#issuecomment-192487290.

**Comment by pixelzoom** [comment]
@schmitzware Initial impression of `GunTargetNode` is that it's a bit of an odd duck.  I have some intuitions about how to factor out a ScreenView base type, but I want to review the requirements for the new "Macro" view (#20) before proposing something half-baked.  Just wanted to let you know in case you dive into addressing code-review issues before I get to this.  I'll now be removing this background task from my brain until next Monday :)

**Comment by pixelzoom** [comment]
The differences between the 2 ScreenViews are:

(1) They use different subtypes of ParticleSpaceNode
(2) RutherfordAtomScreenView has an additional control panel for atom properties (AtomPropertiesPanel).

I created a branch named 'screenview-refactor' to demonstrate how to factor out a ScreenView base type. (That branch is documented in https://github.com/phetsims/rutherford-scattering/issues/54 and will be deleted when this issue is closed.)

The basic idea is:

(1) Move code shared by RutherfordAtomScreenView and PlumPuddingAtomScreenView to a new base type, RSBaseScreenView.
(2) Subtypes of RSBaseScreenView provide a function (`createSpaceNode`) to create the proper subtype of ParticleSpaceNode.
(3) RutherfordAtomScreenView adds the AtomPropertiesPanel via `options.additionalPanels`.

I also added some notes to RutherfordAtomScreenView about how this refactor supports the new 'Atom' view that is requested in #20.   See //TODO at the end of the constructor.

@schmitzware let's discuss after you've had a look.

**Comment by schmitzware** [comment]
Yeah, I agree theGunTargetNode is an odd duck but it breaks it up so it's at least easy to tweek in the two screens. The approach you outline in the branch is close to where I was originally headed when I brought it up the first time.  I'll redo it.

**Comment by schmitzware** [comment]
Ok.. that IS much nicer and you basically did all the work so I take back my whining..  ;)

**Comment by pixelzoom** [comment]
Two minor things:

RSBaseScreenView, change to `@author Dave Schmitz (Schmitzware)`, I just moved your code.

RutherfordScatteringScreenView comment contains a leading '+', probably from a merge:
```43 +   * Create the node in which atoms and alpha particles are rendered.```

**Comment by pixelzoom** [comment]
And feel free to close...
