### ISSUE TITLE
unnecessary coupling in GunTargetNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#50]
Related to #30 (code review).

The constructor for GunTargetNode is:

```js
  /**
   * @param {RSBaseModel} model
   * @param {Object} [options]
   * @constructor
   */
  function GunTargetNode( model, options ) {
```

There's unnecessary coupling here.  GunTargetNode only needs access to `model.gun`.   Recommended to change to:

```js
  /**
   * @param {GunModel} gun
   * @param {Object} [options]
   * @constructor
   */
  function GunTargetNode( gun, options ) {
```

**Comment by pixelzoom** [comment]
Before you fix this, you might want to review #49 (comment), where I've proposed to delete GunTargetNode.

**Comment by schmitzware** [comment]
As #44 - already started working on.

**Comment by pixelzoom** [comment]
:+1: Closing.
