### ISSUE TITLE
add translated strings to babel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#56]
This is a development task, mentioned in the master checklist #15:

> Port existing strings (IF ANY) and commit to the GitHub repo

Awhile back, strings for all Java sims were converted to JSON using a batch process, and they live in babel/autoport/.

So this involves moving `babel/autoport/rutherford-scattering/` to `babel/rutherford-scattering/`, and "fixing up" any string keys that may have changed.  Looks like we can globally remove 'string.' from the translated files and we should be in decent shape.  

@schmitzware Do you want to collaborate on this, or give it a go yourself?

**Comment by schmitzware** [comment]
I can do it. But just so I understand:

1. cp babel/autoport/rutherford-scattering babel/rutherford-scattering
2. match up the keys in each file with those in rutherford-scattering-strings_en.json
3. commit/push

?

**Comment by pixelzoom** [comment]
Yup.  

Looks like you can globally replace:

'string.' -> ''
'.name' -> '.title'

There's 1 unused key in the ported strings, "int.minControlPanelWidth", up to you whether to delete it. It will never be visible to the translator, what the translator sees in Rosetta (translation UI) is what's in the English string file.

**Comment by pixelzoom** [comment]
And if it's too messed up, you can also just punt.  The goal is to provide a starting point for translations if possible, but to rely on the translators to do most of the work.

**Comment by schmitzware** [comment]
Ok..  I have it in a babel branch (rutherford-scattering). do you want to look at it or should I just merge it?

Looks like these are not used (at least by me) but I didn't remove them:

"rutherford-scattering.description": 
"int.minControlPanelWidth": 
"string.turnOnTheGun":

**Comment by pixelzoom** [comment]
"translation.credits" is also unused, never present in English, added to translations by the Java/Flash translation utility. Safe to ignore it.

I looked at a couple of random locales (ar, it, pt) and they look good to me. I'd say go ahead and merge, then delete the branch.

**Comment by pixelzoom** [comment]
Looks good to me.  

I deleted babel/autoport/rutherford-scattering in https://github.com/phetsims/babel/commit/a2d316cd34634ec4c8700616bf6cc5cbe64a4a25.
Ignore https://github.com/phetsims/function-builder/commit/ce38f105dd100cce5b4d459bc0140499bd50941e where I accidentally pushed some function-builder changes.

Assigning to @jbphet.  Since the last time I ported strings was pre-Rosetta, please take a look at the files in babel/rutherford-scattering.  Also do your Rosetta magic on figaro.  Thanks.

**Comment by jbphet** [comment]
Files look reasonable, and the Rosetta incantation has been performed.  Closing.
