### ISSUE TITLE
Dev test Rutherford Scattering 1.0.0-dev.1

### ISSUE THREAD

**Issue by schmitzware** [phetsims/rutherford-scattering#57]
http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.1/rutherford-scattering_en.html

**Comment by schmitzware** [comment]
http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.1/rutherford-scattering_en.html

**Comment by ariel-phet** [comment]
@schmitzware testing tasks should be made in the tasks repo.

Moving this issue there and will flesh out and assign https://github.com/phetsims/tasks/issues/545

closing
