### ISSUE TITLE
Increase transparency of alpha particle beam in "atom" scene

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/rutherford-scattering#64]
To give a feel that in the atom scene the alpha particle beam is more diffuse lets make the beam more transparent in addition to being wider. Basically this beam should feel a dimmer and the nucleus scene should feel brighter.

**Comment by ariel-phet** [comment]
Looked at this on the latest pull from master. Looks good to me. Close if you wish @jessegreenberg

**Comment by jessegreenberg** [comment]
Great, thanks @ariel-phet!
