### ISSUE TITLE
Scene radio button design

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#65]
Related to #20, @emily-phet had the following thoughts and recommendations regarding the scene radio buttons:

> The visual weighting of these buttons seems the same as everything else on the screen - I’m not sure that folks will find them readily (maybe this has been checked in interviews?). If you would like students to find these buttons relatively early in exploration, I would suggest considering putting the buttons in the lower right, under the toolbar, or considering having the whole buttons colored (rather than outlined in color). Essentially, something to help them not get lost on the screen.

>If you would like them to not focus on those buttons too early, I would suggest perhaps considering highlighting other regions of the screen more…maybe laser button and the control panel. Right now there are a lot of black spaces with light colored borders and it’s not clear to me from the visual layout exactly what I might want to focus on initially.

@amyh-phet also mentioned:
> I also was wondering if we would want to use icons instead of words for the scene buttons to avoid issues with resizing the buttons for translations.

@amyh-phet how would you like to proceed?

**Comment by jessegreenberg** [comment]
Regarding translations, the radio button text is scaled for i18n.  For example triple length looks like
![triple](https://cloud.githubusercontent.com/assets/6396244/15730134/37d8f5ea-2827-11e6-83ee-5c7989017c5d.PNG)

Icons could still be useful, but what do you think @amyh-phet?

**Comment by amyh-phet** [comment]
@jessegreenberg  Looks like we have room for translation, but I think icons might just be easier.  I can work on them today and send you the file.

**Comment by jessegreenberg** [comment]
Files received via email, adding them in today and assigning to myself.

**Comment by jessegreenberg** [comment]
To fit the new icons, we will need to bring the particle down just a bit.

**Comment by amyh-phet** [comment]
Icons worked well in student interviews.  Closing.
