### ISSUE TITLE
Should particles avoid the center of the space?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#66]
For the nucleus scene, the gun prevents particles from firing directly through the center of the space

```js
var particleX = ySign * ( X0_MIN + ( RAND.random() * ( ( this.model.bounds.width / 2 ) - X0_MIN ) 
```

This is undesirable for the atom scene since we want particles to occasionally scatter of the center atom.  Is there a reason to keep this behavior for the 'nucleus' scene?

**Comment by jessegreenberg** [comment]
@phet-steele just pointed out that occasionally the particles will cuddle up into the atom.  When the particles come directly through the center, this effect is even more obvious.

![alphacuddlev2](https://cloud.githubusercontent.com/assets/6396244/15762593/e1279d54-28db-11e6-8e6a-72206564568e.PNG)

**Comment by jessegreenberg** [comment]
The trajectory algorithm has a value L_DIVISOR which we might be able to tweak so that particles shy away from the nucleus a bit more.  But I have no idea what this is doing in the context of the physical model.  And if this L_DIVISOR is low enough to prevent particles from hitting the nucleus, they are too sluggish when energy is low.

**Comment by amyh-phet** [comment]
@jessegreenberg   I will look into this tonight to see what L_DIVISOR is doing in the model.

**Comment by jessegreenberg** [comment]
Thanks @amyh-phet! From trajectories.pdf

> For Bohr/deBroglie/Schrodinger, D = Db = L/16, (We'll probably need to tweak this number a bit).

L_DIVISOR is the value 16, currently at value 8 in the implementation.

**Comment by amyh-phet** [comment]
@jessegreenberg   Thanks for the clarification of the number actually used in implementation.  One quick question that I can't figure out from the model documentation.  How are the coordinates for x set up?  If x=0 initially, does that correspond to the center of the nucleus (basically the center of the box) or does it refer to the left-most edge of the box?

**Comment by jessegreenberg** [comment]
The coordinate frame for trajectories assumes that the atom nucleus is at ( 0, 0).  I just found some notes ini the Java that might be helpful.  I will add them to the JavaScript.

>      * ASSUMPTIONS MADE IN THIS ALGORITHM: 
     * (1) The atom is located at (0,0).
     * This is not the case in our model. So coordindates are adjusted 
     * as described in the comments.
     * (2) +y is up.
     * Our model has +y down. So we'll be adjusting the sign on y 
     * coordinates, as described in the comments.
     * (3) alpha particles are moving from bottom to top
     * (4) x values are positive.
     * The algoritm fails for negative values of x. This is not
     * mentioned in the specification document. So we have to convert
     * to positive values of x, then convert back.
     * (5) Using "phi=arctan(-x,y)" as described in the spec causes
     * particles to jump discontinuously when they go above the y axis.
     * This is fixed by using Math.atan2 instead.
     * (6) Depending on the parameters supplied, the algorithm will tend
     * to fail as the alpha particle's horizontal position (x) gets closer
     * to zero. So the Gun model is calibrated to fire alpha particles 
     * with some min initial x value.

**Comment by jessegreenberg** [comment]
> (6) Depending on the parameters supplied, the algorithm will tend to fail as the alpha particle's horizontal position (x) gets closer to zero. So the Gun model is calibrated to fire alpha particles with some min initial x value.

This is our answer!

**Comment by jessegreenberg** [comment]
Also, at the bottom of https://github.com/phetsims/rutherford-scattering/blob/master/doc/trajectories.pdf

> Note: You will run into divide by zero problems when b=0.  I would advise just making sure that x0 is never exactly zero...

**Comment by amyh-phet** [comment]
@jessegreenberg   Good catch.  I think the problem is when x=0, the loop for calculating the new x,y coordinates of the alpha particle fails because we get a situation with a 0 in the denominator.

**Comment by jessegreenberg** [comment]
@amyh-phet that would make a lot of sense.  When x0 is exactly zero, it will hiccup a bit in the 'Atom' scene (single particle shown below)
![recording 13](https://cloud.githubusercontent.com/assets/6396244/15785934/39c67cbe-2977-11e6-87cf-dad41f3e5ea5.gif)

And particles in the 'Nucleus' scene fail too quickly to appear in the space.

**Comment by amyh-phet** [comment]
@jessegreenberg   Any ideas on how to address this issue?  Need anything from me?

**Comment by amyh-phet** [comment]
@jessegreenberg   Sounds like a reasonable fix.  Thanks for tracking down the source of the error.

**Comment by jessegreenberg** [comment]
Fixed in the commit above, the position correction (X0_MIN)  from the gun is now a function of the atomic bounds, now var xMin.  Correction is only applied if the particle if the particle x0 is within xMin from the atomic nucleus.  Closing.
