### ISSUE TITLE
sim fails at startup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#7]
Difficult to test #6 because this sim doesn't run. In developer mode, it fails at startup with this error:

> Uncaught TypeError: Cannot read property 'replace' of undefined :  RutherfordAtomView.js?bust=1431729951890:50 Uncaught TypeError: Cannot

**Comment by jonathanolson** [comment]
Still occurring in automated testing.

**Comment by jakies** [comment]
Went ahead and commented it out in https://github.com/phetsims/rutherford-scattering/commit/a034b9e4ee24cb89d05fecb183ba682d46b24256 real quick. Should prevent the error while I convert over to the new standard for template screens

**Comment by pixelzoom** [comment]
rutherford-scattering removed from active-runnables. Closing.
