### ISSUE TITLE
Count tweakers reset the alpha particles when clicked at min or max

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/rutherford-scattering#70]
For phetsims/tasks#627
Test Device: Personal Laptop
Operating System: Mac OSX 10.11.5
Browser: Safari

Problem Description: On the Rutherford Atom screen, the proton and neutron count tweakers reset the alpha particles even when clicked at min or max.

Steps to Reproduce:
1. Select the Rutherford Atom screen
2. Move the number or protons and/or neutrons to the min or max setting
3. Click the count tweaker, the alpha particles will reset

![rs01](https://cloud.githubusercontent.com/assets/19288972/16315151/52106a10-393e-11e6-82f1-b48570eb4153.gif)

Name: ‪Rutherford Scattering‬
URL: http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.5/rutherford-scattering_en.html
Version: 1.0.0-dev.5 2016-06-23 17:08:25 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17
Language: en-us
Window: 1423x763
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 ATI-1.42.11)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"047295f6","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"e044eccd","branch":"master"},"dot":{"sha":"551f726f","branch":"master"},"joist":{"sha":"a42bced7","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"rutherford-scattering":{"sha":"bb298184","branch":"master"},"scenery":{"sha":"4476eb95","branch":"master"},"scenery-phet":{"sha":"52b783d9","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"shred":{"sha":"95e9e909","branch":"master"},"sun":{"sha":"0d7e743b","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by jessegreenberg** [comment]
Great catch @alynne-phet, thanks.

**Comment by alynne-phet** [comment]
Fixed, closing.
