### ISSUE TITLE
iPad 2 performance problems

### ISSUE THREAD

**Issue by andrea-phet** [phetsims/rutherford-scattering#71]
Test device: TYCHO (iPad 2)

Operating System: iOS 9.3.3

Browser: Safari/601.1

Problem description: These problems are seen on iPad 2 but haven't been seen on windows, mac, chrome or firefox. @phet-steele @alynne-phet 

Steps to reproduce:
Problem 1. Alpha particles sometimes disappear when they directly/close to directly hit a rutherford nucleus, instead of bouncing off.
1. Choose Rutherford Atom screen
2. Choose the macro view
3. Set alpha particle energy to max (problem more likely to occur with higher energy)
4. Enable Traces (optional, but it helps you see the particles disappear better)
5. Click the blue button on the gun, and watch the nucleuses for this to happen (the video is sideways, but it happens on the top right nucleus):
https://drive.google.com/open?id=0B_qcKyUiFT4Mb0hyZGd1ajJjR2M

Problem 2. Clicking the pause button causes particles to stop, go forward a couple pixels, and then actually pause. Happens in any screen, any scene, any energy value for the particle.
1. Go to the Rutherford Atom or Plum Pudding Atom screen
2. Choose any scene
3. Turn on the gun
4. Click pause

Problem 3. The action after clicking the play button experiences lag.
The particles seem to be moving in the background (in the model?) without the screen catching up, because when the particles start moving on the screen again, it's from a different location (further down their path).
1. Repeat steps in problem 2
2. Click play
https://drive.google.com/open?id=0B_qcKyUiFT4MNExybS1GNWRiVHM

Problem 4. Clicking arrows on the protons and neutrons spinner take a long time to change the number, making it difficult to increment the number quickly. Holding down the arrows are fine. Quickly dragging the slider back and forth experiences some lag as well, but this lag isn't seen, for example, in the alpha particle energy slider.
1. Choose the Rutherform Atom screen.
2. In the Atom panel on the right, click the spinner arrows or quickly drag the slider back and forth
https://drive.google.com/open?id=0B_qcKyUiFT4MNE83NzhVM2E5c0U

Troubleshooting information (do not edit):
Name: ‪Rutherford Scattering‬
URL: http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.5/rutherford-scattering_en.html
Version: 1.0.0-dev.5 2016-06-23 17:08:25 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G21 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"047295f6","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"e044eccd","branch":"master"},"dot":{"sha":"551f726f","branch":"master"},"joist":{"sha":"a42bced7","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"rutherford-scattering":{"sha":"bb298184","branch":"master"},"scenery":{"sha":"4476eb95","branch":"master"},"scenery-phet":{"sha":"52b783d9","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"shred":{"sha":"95e9e909","branch":"master"},"sun":{"sha":"0d7e743b","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by andrea-phet** [comment]
For phetsims/tasks/issues/627

**Comment by brroberts1231** [comment]
The alpha particles disappearing when hitting atoms dead on has been seen on IE11 and Edge as well.

**Comment by jessegreenberg** [comment]
Thanks for catching these!  I am going to break this up into separate issues and reference this once since there is a fair amount to track here.

**Comment by jessegreenberg** [comment]
@andrea-phet do you observe problem 4 for both scenes of the Rutherford Atom screen?

**Comment by andrea-phet** [comment]
Yes, problem 4 occurs on both scenes. Just tested it.

**Comment by jessegreenberg** [comment]
Ok, thanks @andrea-phet.

**Comment by alynne-phet** [comment]
Fixed, closing. Problem one is being tracked in issue #74.
