### ISSUE TITLE
Remove Electron from legend on Rutherford Atom screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/rutherford-scattering#72]
@jessegreenberg 

We need to remove Electron from the legend in the Rutherford atom screen as no electrons are shown on this screen.

**Comment by jessegreenberg** [comment]
@amyh-phet this version has the electron removed:  http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.7/rutherford-scattering_en.html

Closing, but if something seems incorrect please let me know.
