### ISSUE TITLE
Scale label on Rutherford and Plum Pudding screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/rutherford-scattering#73]
On Rutherford Atom screen:
1) On nucleus view, change current label [150 fm (nuclear scale)]  to read:     1.5 x 10<sup>-13</sup> m (nuclear scale)
2) On atom view, change current label  [600 pm (atomic scale)] to read:    6.0 x 10<sup>-10</sup> m (atomic scale)

On Plum Pudding Atom screen, change current label [300 pm (atomic scale)] to read:  3.0 x 10<sup>-10</sup> m (atomic scale)

**Comment by jessegreenberg** [comment]
@amyh-phet this dev version includes this change.

http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.7/rutherford-scattering_en.html

Would you mind reviewing?  If acceptable, please close.

**Comment by amyh-phet** [comment]
Looks great.  Closing
