### ISSUE TITLE
Visual cue for 'plum pudding'

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#79]
In 6/30 status meeting, we mentioned that we might need an indication of what the plum pudding blob is in the 'Plum Pudding' screen.  Not sure where we left off on that, assigning to @amyh-phet to track.  If it is not necessary, feel free to close immediately @amyh-phet.

**Comment by amyh-phet** [comment]
@jessegreenberg    I do think adding a label for plum pudding would be in order.  I've attached a copy of the artwork for the legend and a picture of what the new legend should look like.  Let me know if you have questions or need me to revise the artwork in any way. 
![positive_charge_pudding](https://cloud.githubusercontent.com/assets/13650180/16622519/b27d6632-4357-11e6-80b1-338e9779b4ff.png)

![rs_plum_pudding_revised_legend](https://cloud.githubusercontent.com/assets/13650180/16622484/95c3536c-4357-11e6-9489-c8f4ff5d592b.png)

**Comment by jessegreenberg** [comment]
Commit above adds this to the legend.

**Comment by jessegreenberg** [comment]
@amyh-phet would you mind reviewing the change?  Here is the latest dev version:
http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.8/rutherford-scattering_en.html

**Comment by jessegreenberg** [comment]
@amyh-phet would you mind reviewing the new icon in the legend?

Here is the latest version:
http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.8/rutherford-scattering_en.html

**Comment by amyh-phet** [comment]
Looks good. Thanks for implementing.

**Comment by jessegreenberg** [comment]
Great thanks @amyh-phet.  Closing.
