### ISSUE TITLE
Label for alpha particle gun

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#80]
In 6/30 status meeting, @amyh-phet mentioned that the label might need to be added back to the particle gun.  Creating this issue just to track status.

**Comment by amyh-phet** [comment]
@jessegreenberg   I do think we need to add the Alpha particle label back on the alpha particle source.  In interviews, student took a long time to turn on the source, so something to draw their attention to the source is needed.

**Comment by jessegreenberg** [comment]
@andrea-phet added this in the commit above, closing.
