### ISSUE TITLE
Design: Should gun beam width and tiny box size match

### ISSUE THREAD

**Issue by schmitzware** [phetsims/rutherford-scattering#86]
Seems like box size on the gold foil should be resized to match the beam width. If the beam represents the larger area, then the exposed area on the gold foil (which is the zoomed sim area) should be larger.

![screen shot 2016-07-19 at 12 41 19 pm](https://cloud.githubusercontent.com/assets/694045/16964021/243eae1a-4dae-11e6-8a4d-91002e37550a.png)

**Comment by jessegreenberg** [comment]
@schmitzware that makes sense to me, @amyh-phet and @ariel-phet since this is a design question you you agree?

**Comment by amyh-phet** [comment]
@jessegreenberg  The little box on the gold foil is meant to convey that the view is looking only at a small portion of the sample.  I don't think the beam width needs to match the size of the little box that represents what we are viewing.  I do think it looks a bit odd to have the beam size change between the two views on the Rutherford screen.  I know we were trying to convey an idea of viewing a more concentrated beam of alpha particles on the nucleus view and a more diffuse beam on the atom view.  My preference would be to use the larger beam for all three views but keep the darker shading for the beam on the nucleus view.

@ariel-phet    Any feedback?

**Comment by ariel-phet** [comment]
Two things:

1. I would be fine with not changing the beam diameter (but still varying the shading to convey intensity)

2. I would adjust the dashed lines so they go to the center on the top and bottom of the small box, that seems to be more standard when I do a google image search for conveying a "zoomed" view

**Comment by amyh-phet** [comment]
@jessegreenberg   Let's do the following:

1) Keep beam diameter consistent across all screens (so size of beam would need to be increased on Rutherford screen, nucleus view).

2) Keep beam shading/intensity as currently implemented. (Beam is lighter on Rutherford screen, atom view and Plum Pudding,  more shaded in on Rutherford screen, nucleus view).

3) Adjust the dashed lines so the go to the center of the top and bottom of the small box in the gold foil.

**Comment by jessegreenberg** [comment]
Here is a new dev version with the change, @amyh-phet could you please review?

http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.9/rutherford-scattering_en.html

**Comment by amyh-phet** [comment]
@jessegreenberg    Looks good on the Rutherford Atom screen.  On the Plum Pudding screen, the beam intensity is too bright.  It should look just like the beam on the Rutherford screen - Atom view.

**Comment by jessegreenberg** [comment]
Thanks Amy, is this better? 

http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.10/rutherford-scattering_en.html

**Comment by amyh-phet** [comment]
Looks great!
