### ISSUE TITLE
RutherfordNucleus.js: add documentation on when no unlink/dispose are needed.

### ISSUE THREAD

**Issue by schmitzware** [phetsims/rutherford-scattering#88]
Seems like this issue has popped up in discussions and added recently added to the checklist:

> For each common-code component (sun, scenery-phet, vegas, …) that opaquely registers observers or listeners, is there a call to that component’s dispose function, or documentation about why dispose is unnecessary?

Kinda seems like overkill to me if there's no memory leaks (which there are not) but I thought I'd mention it. There's most likely other files where this is relevant as I believe this came up after I did the original JS version.  I'll just assume this issue covers those and leave it up to you to decide if we want go back and document this or not.

```
    protonCountProperty.link( function( protonCount ) {
      configureNucleus( protonCount, 'proton' );
    } );

    neutronCountProperty.link( function( neutronCount ) {
      configureNucleus( neutronCount, 'neutron' );
    } );
  }

  rutherfordScattering.register( 'RutherfordNucleus', RutherfordNucleus );

  return inherit( ParticleAtom, RutherfordNucleus );
```

**Comment by jessegreenberg** [comment]
I just tested this the memory and it seems that there is a bit of a memory leak at the moment.  The following was observed with fuzzMouse=100.

![capture](https://cloud.githubusercontent.com/assets/6396244/17026279/8f0fffa2-4f2d-11e6-87eb-552f3e84a878.PNG)

**Comment by schmitzware** [comment]
Interesting..  I actually looked it with just "fuzzMouse" and the memory usage looked good. What's the "100" do?

**Comment by jessegreenberg** [comment]
Yes, it is pretty small.  I noticed a couple possible culprits while going through the sim for #92, and both are related to my new additions. Since this is an issue about documentation, Ill create a new issue to track the leak.

**Comment by jessegreenberg** [comment]
I added some documentation around observer registrations where disposal is unnecessary and added dispose functions in cases where it might be helpful in the future. Closing.
