### ISSUE TITLE
Projector view?

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/rutherford-scattering#92]
Hate to bring this up so late in the game, but do we need to incorporate a projector mode for RS?   When Steele was working on a video for BCCE, he recorded a clip from RS and we noticed it was really hard to see the alpha particles and traces on all screens.  It was also hard to see the electron energy levels on the atom view scene.

Thoughts @ariel-phet  and @jessegreenberg?

**Comment by phet-steele** [comment]
Some words in the panels were hard to see, too, like the "Protons" label for the sliders.

**Comment by ariel-phet** [comment]
@amyh-phet good thought...I think this is actually not too bad. I believe @jonathanolson set things up in molecule shapes in a way that is pretty easily generalized/copied. 

@jessegreenberg when you get a chance can you investigate and use molecule shapes as a template?

**Comment by jessegreenberg** [comment]
Sure, I will take a look.

**Comment by jessegreenberg** [comment]
Since the plum pudding image has a black background, it will show up with a different color background in projector mode.  @amyh-phet would you mind sending me a new image for the plum pudding goo with a a transparent background?

**Comment by amyh-phet** [comment]
@jessegreenberg   

Here is the plum pudding model (used in the view of the plum pudding screen - shows electrons)
![plum_pudding](https://cloud.githubusercontent.com/assets/13650180/17141957/76df3772-530b-11e6-937a-2b12c3695d65.png)

I wasn't sure if you also needed the image for the legend on the plum pudding screen, so here is the image for the legend (no electrons - just red blob).
![positive_charge_pudding](https://cloud.githubusercontent.com/assets/13650180/17142127/3937b6f0-530c-11e6-8d1f-f2010851cd80.png)


Let me know if you need other assets for implementing

**Comment by jessegreenberg** [comment]
Here is a new version with a 'Projector' option added.  We still need to determine the colors for projector mode. @amyh-phet and @phet-steele if you have access to a projector, can you use this version to determine the colors that are best for visibility with a projector?

http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.11/rutherford-scattering-colors_en.html

The panel on the left will change the colors in the sim.  You won't be able to change the colors for everything, but if you switch to projector mode in options, everything that can be changed will go white.  If something else needs to be added to the list of changeable colors, please let me know.

**Comment by jessegreenberg** [comment]
One caveat: If the color of electrons needs to change, we will need to either have a second image for the plum pudding or draw the electrons with Scenery since they are static in the image.

**Comment by amyh-phet** [comment]
@jessegreenberg   Happy to test with the projector in the office today.  Not sure that @phet-steele has access to a projector right now.

**Comment by amyh-phet** [comment]
@jessegreenberg   What is the best way to communicate final color choice for this screen?

**Comment by jessegreenberg** [comment]
Thanks @amyh-phet!  Would you mind listing them here by name in the panel in the version above? For instance ```panelLabel = xxx``` and so on?

**Comment by amyh-phet** [comment]
@jessegreenberg   Happy to do that.  Hexcode the easiest?

**Comment by jessegreenberg** [comment]
@amyh-phet rgb would be easiest, but whatever is most conveneint.

**Comment by amyh-phet** [comment]
**background = 255, 255, 255**
**radioButtonBorder = 49, 193, 221**
panel = 0, 0, 0   (I honestly couldn't tell what this controlled on any of the screens/scenes)
panelBorder =128, 128, 128 
**panelTitle = 0, 0, 0 
panelSilder = 0, 0, 0, 
panelLabel = 0, 0, 0**
protonsLabel = 185, 50, 8
**neutronsLabel = 125, 125, 125**
atomBeam = 143, 143, 143
**nucleusBeam = 163, 163, 163**
particleSpecularHighlight = 200, 200, 200
alphaNucleusTrace = 128, 128, 128
electronColor = 135, 135, 205
protonColor = 255, 69, 0
neutronColor =192, 192, 192
particleColor = 255, 0, 255
**nucleusColor = 128, 128, 0**
energyLevelColor=128, 128, 128
materialFrontColor = 214, 203, 134
materialBackColor =  140, 126, 41

I didn't see a way to change this, but the following items should also be black:
slider tracks and labels
Traces checkbox
Scale label below view box in all screens - all text, the arrows, and the end tick marks showing the distance measured

**Comment by amyh-phet** [comment]
@jessegreenberg   Attached is a new file for the atom scene selection button for use in projector mode.  Let me know if you need the AI version of the file.
![atom_scene_selection_button_projector](https://cloud.githubusercontent.com/assets/13650180/17158133/4a2dff6a-5351-11e6-9c91-1fe40ff8a9ef.png)

**Comment by jessegreenberg** [comment]
Thanks @amyh-phet, I will add these in.

> I honestly couldn't tell what this controlled on any of the screens/scenes

Sorry, it doesn't do anything.  I should have double checked the list.

> Let me know if you need the AI version of the file.

Yes, could you please send the AI file?

**Comment by amyh-phet** [comment]
@jessegreenberg    Just sent AI file to you via email.  Let me know if you need anything else.

**Comment by jessegreenberg** [comment]
Projector mode complete with the above commits, @amyh-phet or @phet-steele would you please review and make sure that the colors are correct and look good on a projector?  Here is the latest version:

http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.12/rutherford-scattering_en.html

**Comment by amyh-phet** [comment]
@jessegreenberg   Looking pretty good, but I noticed that the  "Alpha Particle" label below source should be black. Current gray color is hard to see.

**Comment by jessegreenberg** [comment]
Sorry about that, here is a new version with that fixed if you would like to take a look.
http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.13/rutherford-scattering_en.html

@amyh-phet anything else to do for this issue?

**Comment by amyh-phet** [comment]
@jessegreenberg   Looks great.   Nothing else here, so closing.
