### ISSUE TITLE
Should this repo be in active-runnables?

### ISSUE THREAD

**Issue by samreid** [phetsims/rutherford-scattering#94]
I was surprised to discover that this simulation wasn't listed in active-runnables. Is it ready for that?

**Comment by phet-steele** [comment]
@jessegreenberg @schmitzware This sim certainly needs to be in active-runnables. It's very near completion and has been through multiple rounds of QA testing. Thanks @samreid for noticing!

**Comment by schmitzware** [comment]
I'll leave this up to you, Jesse. Let me know if you need anything from me.

**Comment by jessegreenberg** [comment]
Thanks all, added!
