### ISSUE TITLE
Atom properties panel content shifts with use of sliders

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/rutherford-scattering#97]
Firist observed after some fuzz testing, but setting the slider thumbs to their min value shifts the content of the panel to the left.  If done repeatedly it is possible to shift the content all the way outside of the panel box.
![capture](https://cloud.githubusercontent.com/assets/6396244/17335667/f7c723fe-5897-11e6-8d1d-9d3c04ca9b11.PNG)

**Comment by jessegreenberg** [comment]
Content was in a VBox.  Preventing it from resizing fixes the issue.  Closing.

**Comment by phet-steele** [comment]
Occurs in Alpha Particle Energy panel as well with short strings, eg. `?stringTest=X`. For phetsims/tasks/issues/667

**Comment by phet-steele** [comment]
Looks good!
